### ISSUE TITLE
Plugin doesn't list the annotations Zotero app has

### ISSUE THREAD

**Issue by volker-fr** [mgmeyers/obsidian-zotero-integration#107]
I have document where the Zotero Data Explorer doesn't show any PDF annotations. If I query the item against the Zotero API, I see all the annotations.

Note: The Data Explorer main id is the parent object of the PDF. The PDF itself has its own id that can be found in the pdfLink key of the Data Explorer result. I used the API here since its easier for me to demonstrate the issue since the Zotero application doesn't show the id itself.   The same annotations the API returns can also be found in the local Zotero application, which this plugin contacts directly.

Data explorer:

![data-explorer](https://user-images.githubusercontent.com/4174391/194968656-95eb5bd2-66c9-4e15-adae-16a13309155d.png)

API query:
![api-result](https://user-images.githubusercontent.com/4174391/194968681-f5bfac28-a2d2-462d-b276-a5de21648cec.png)

Error console of Obsidian is empty on Data Explorer pull.

Other PDFs/imports in Obsidian have their annotations.

Since the Data Explorer doesn't see it, these annotations can also not be imported.

**Comment by mgmeyers** [comment]
@volker-fr I see there are two attachments for this item, are they both PDFs?

**Comment by volker-fr** [comment]
> @volker-fr I see there are two attachments for this item, are they both PDFs?

This is a good catch. One is a HTML, the other a PDF:

```
>>> for i in ZOT.children("T9WJUFIT"):
...     if 'contentType' in i['data']:
...             print(i['key'], i['data']['itemType'], i['data']['contentType'])
...     else:
...             print(i['key'], i['data']['itemType'])
... 
RBKIMNSN note
6WQX2DRF attachment application/pdf
QEJUAT9S attachment text/html
```

The way I create most Zotero entries is:
1. Use Zotero browser connector in Chrome
2. Browser plugin setting is "Automatically take snapshots when saving items"
3. Have the PDF also automatically downloaded
4. Just create my own note/short summary


Now I moved the website snapshot out of the parent item and the Data Explorer finally sees the annotations. The other item where it worked has no such snapshot and only the PDF, which explains why in most cases the import had no annotation.

Seems like for some reason the plugin looks for annotations of the html/snapshot file -- which doesn't have an annotation feature in Zotero.


Outside of this issue, it also raises the question how it behaves if an item has two PDFs attachments (which should be much more rare).

**Comment by volker-fr** [comment]
The issue seem to be based on [`getAttachmentsFromCiteKey()`](https://github.com/mgmeyers/obsidian-zotero-integration/blob/main/src/bbt/jsonRPC.ts#L107).

It does the following call to better bibtex
```
      ...
      url: `http://127.0.0.1:${getPort(database)}/better-bibtex/json-rpc`,      
      body: JSON.stringify({                                                    
      jsonrpc: '2.0',                                                         
      method: 'item.attachments',                                             
      params: [citeKey], 
      ...
```

The response here is
```

**Comment by volker-fr** [comment]
I came across https://github.com/retorquere/zotero-better-bibtex/issues/2092 which references a shortfall documented in https://github.com/retorquere/zotero-better-bibtex/issues/2126

**Comment by mgmeyers** [comment]
Ah, I think that error comes from a PR I made to better bibtex (https://github.com/retorquere/zotero-better-bibtex/pull/2192). I think there needs to be a check here to see if the attachment is a file attachment: https://github.com/retorquere/zotero-better-bibtex/blob/master/content/json-rpc.ts#L169

**Comment by mgmeyers** [comment]
Ok, made a PR to better bibtex to fix this: https://github.com/retorquere/zotero-better-bibtex/pull/2279

**Comment by mgmeyers** [comment]
@volker-fr Try updating better bibtex and see if this issue is fixed for you

**Comment by volker-fr** [comment]
@mgmeyers Updated to better bibtex version 6.7.26. The issue seem to be resolved now.

Thanks a lot for your help :)

**Comment by volker-fr** [comment]
Reopening. Wondering if the the bibtex change broke image import of annotations. https://github.com/retorquere/zotero-better-bibtex/pull/2279

**Comment by volker-fr** [comment]
Change in better bibtex seems to not impact image imports. Closing again.

**Comment by cwarp301** [comment]
Hello! I am pretty sure I still have this issue. Better bibtex is up to date. 

<img width="596" alt="image" src="https://github.com/mgmeyers/obsidian-zotero-integration/assets/146747891/66a559fc-555d-4cb1-be5a-94b1851bd59f">


This is a PDF but its not searchable.

**Comment by f4n745y** [comment]
Hi, I have also encountered the same problem. BetterBibtex and Obsidian Zotero Integration are up to date. However, the parent items in question have only one attachment (a pdf).

**Comment by cmosguy** [comment]
I have latest obsidian and zotero extensions installed and the import is yielding nothing.

**Comment by FeralFlora** [comment]
> I have latest obsidian and zotero extensions installed and the import is yielding nothing.

It might be a template issue.

**Comment by Fenrihr** [comment]
> I have latest obsidian and zotero extensions installed and the import is yielding nothing.

I'm having the same problem: the import is yielding nothing.

My instalation:
- SO: Fedora Linux 39 (Workstation Edition)
- Zotero: 6.0.30 (via Flatpak)
- Better BibTex for Zotero: 6.7.148
- Obsidian: 1.5.3 (via Flatpak)

![imagen](https://github.com/mgmeyers/obsidian-zotero-integration/assets/380335/4958eeba-2f8e-4806-8350-6f094eb90261)

**Comment by FeralFlora** [comment]
There could be many reasons why some of you are having issues, including incorrect template setups or import format configurations. Therefore, it would be best to create new issues where you include your template.

If the Data Explorer is showing the annotations, like in the screenshot above, then a template issue is a likely reason why the annotations are not being imported into the note.
