### ISSUE TITLE
Import issue

### ISSUE THREAD

**Issue by yyqww** [mgmeyers/obsidian-zotero-integration#119]
@mgmeyers 
when i import a reference again, the annotations will disapper, even i don't do anything to my pdf
i use this code for testing.

```
{% for annotation in annotations %}
{% if annotation.annotatedText %}

> {{annotation.annotatedText}}
> {% endif %}
> {% if annotation.comment %}
> {{annotation.comment}}
{% endif %}
{% endfor %}
```

when i fist import this reference, everything is ok
but when i import it again, content between<%for%><%endfor%>will appear in a short time, then disappear.
what happend???

and it's very odd that when i open the reference file and run the command, it will disappear, but i can use ctrl+z to recover the disappearing content.

someone please come help me!

**Comment by yyqww** [comment]
and i have tested it in other's computer, sandbox, vmware-win10, and no one occur this problem. then i reinstall my computer system, this problem still exit..............................

**Comment by yyqww** [comment]
ok now i solve this problem. the problem is in zotero. if your zotero file folder is not in default location, it will appear this problem.

**Comment by sjgknight** [comment]
@yyqww thank's for identifying the issue. How did you solve it? (I may have a similar issue, 
```
Uncaught (in promise) Error: ENOENT: no such file or directory, copyfile 
```
(for annotation images)

**Comment by yyqww** [comment]
> @yyqww thank's for identifying the issue. How did you solve it? (I may have a similar issue,
> 
> ```
> Uncaught (in promise) Error: ENOENT: no such file or directory, copyfile 
> ```
> 
> (for annotation images)

i just change zotero's folder in default location, and the problem solved

**Comment by yyqww** [comment]
@sjgknight i just change zotero's folder in default location
