### ISSUE TITLE
Open-pdf links

### ISSUE THREAD

**Issue by mscott99** [mgmeyers/obsidian-zotero-integration#124]
Hello,

First thanks for this amazing plugin,

I find that the Zotero links available to template only include the "select" links. It would be great to be able to add "open-pdf" links of Zotero as well.

**Comment by tophee** [comment]
have you tried something like this?

~~~nunjucks
{% if annotation.annotatedText -%}
{{annotation.annotatedText}} [(p. {{annotation.pageLabel}})](zotero://open-pdf/library/items/{{annotation.attachment.itemKey}}?page={{annotation.pageLabel}}&annotation={{annotation.id}})
{% endif -%}
~~~
