### ISSUE TITLE
"Could not find any application or handler for zotero://open-pdf/library/items/8VY3BUNI?page=1&annotation=H4MWN456"

### ISSUE THREAD

**Issue by nilrem77** [mgmeyers/obsidian-zotero-integration#125]
hi,
when I click a link in obsidian to go to zotero I get this warning:
"Could not find any application or handler for zotero://open-pdf/library/items/8VY3BUNI?page=1&annotation=H4MWN456"

why?
thanks in advance

**Comment by mgmeyers** [comment]
This seems to be an issue with how zotero is installed or configured. Not sure why this would be.
