### ISSUE TITLE
Export Relations as Citekeys as well as links

### ISSUE THREAD

**Issue by Comprehensive-Jason** [mgmeyers/obsidian-zotero-integration#130]
Currently, relations are exported as Zotero links.

![image](https://user-images.githubusercontent.com/68677082/204119394-5921b173-97f8-4718-ba81-2ffd25332696.png)
Instead of a link, I want to get the citekey of each related reference, as this would allow me to see how each paper relates inside my Obsidian vault by adding `[[ ]]` around each citekey. MDnotes already allows you to do this via the `{{related}}` placeholder, as can be seen [here](https://youtu.be/mMpVMuGBGe8?t=1727) in Bryan Jenk's video. Having this feature in this plugin would be very useful.

**Comment by mgmeyers** [comment]
@Comprehensive-Jason `relations` should now contain the full data of the related item, including the cite key

<img width="470" alt="Screenshot 2022-12-19 at 1 20 19 PM" src="https://user-images.githubusercontent.com/2694747/208526181-4e2e1530-1fe1-462d-8181-92f6b00a7ef3.png">
