### ISSUE TITLE
Tesseract error:  not a valid tesseract language string

### ISSUE THREAD

**Issue by zjllee** [mgmeyers/obsidian-zotero-integration#136]
I left everything on default except the tessearct path being C:\<installatation path>, and i get the above message.

Am I doing anything wrong?

**Comment by DEAN-Cherry** [comment]
I have the same issue. 
![图片](https://user-images.githubusercontent.com/76607677/205239832-88a53690-8b69-4497-a0ea-a263038d4bc1.png)
I found this command from the console in Obsidian and tried it on my terminal. But still got the same error. I also have tried a pure tesseract command and which is working perfectly.

**Comment by mgmeyers** [comment]
@zjllee This should be fixed now. Try updating the plugin and let me know if you still have issues
