### ISSUE TITLE
Import Note with Images

### ISSUE THREAD

**Issue by BeJa1996** [mgmeyers/obsidian-zotero-integration#137]
Heyo,

I usually write a summary with citations and images from a paper via the Zotero Native Reader in the Zotero Notes. I wanted to use the obsidian-zotero-integration to import this note into obsidian. Whereas the formatting works, the images are not shown. 
<img width="500" alt="image" src="https://user-images.githubusercontent.com/44403548/205043289-490a3dca-4966-4919-b0ef-2b9c2fe12c48.png">
I tried it with "Import Notes", and "Insert Notes Into Current Document" and then with a self-written import format and the following template. However, neither via {{markdownNotes}}, nor via the notes directly could I make it work. Is there another way? Or could you integrate an import that also imports the images at their right place?

### Formatted Bibliography

{{bibliography}}
{{tags}}

{% if abstractNote %}
### Abstract
{{abstractNote}}
{% endif %}

### Annotations
{{markdownNotes}}

-----
{% for i in notes %}
{% if i.note %}

> {{i.note}}
{% endif %}
{% endfor %}

**Comment by tophee** [comment]
Try 
~~~
{% if annotation.imageRelativePath -%}
![[{{annotation.imageRelativePath}}]] 
{% endif -%}
~~~

**Comment by BeJa1996** [comment]
Thank you :) . But this only works If I am importing annotation separately. Am I right? I tried it with markdownNotes and Note, but it did not work. Btw. I found this discussion thanks to your answer, and I think my question fits there better:
https://forum.obsidian.md/t/zotero-desktop-connector-import-templates/36310/50?u=beja1996

**Comment by LucienReyes** [comment]
I have a problem.  The annotation.relativeImagePath doesn’t work at all for me. I have the same template snippet as yours.

**Comment by SaschaRoelofs** [comment]
I have the same problem. When I use a custom template, the images are loaded in the image folder. If I use the defualt template, images are linked to zotero. How can I change the default template to use the images instead of the link ?
Because if I use the custom template, the notes are not ordered anymore and I need them to be ordered

**Comment by mgmeyers** [comment]
@BeJa1996 "Import Notes" and "Insert Notes Into Current Document" will now import images. Update and let me know if you run into any issues

**Comment by williamium3000** [comment]
@mgmeyers When I "Import Notes" or "Insert Notes Into Current Document", only the text is imported.
I am using zotero 7 with better notes.

<img width="706" alt="截屏2025-01-04 上午9 02 25" src="https://github.com/user-attachments/assets/b197f01f-c710-4588-b078-aa0f6273b150" />

After "Insert Notes Into Current Document", only the text is imported.

<img width="745" alt="截屏2025-01-04 上午9 03 08" src="https://github.com/user-attachments/assets/d3d36af8-d96e-4f5c-9d43-60baefd50ddc" />
