### ISSUE TITLE
For citation, how do I output Zotero's citekey?

### ISSUE THREAD

**Issue by ReaderGuy42** [mgmeyers/obsidian-zotero-integration#140]
I'd like the plugin to output something like `\cite{{{citekey}}}`with the inner most brackets being required for LaTeX to render it as a citation. How would I do this? I've tried inverted commas, but they still appear in the citation then.

Any ideas?

**Comment by mgmeyers** [comment]
@ReaderGuy42 Does the latex citation format do what you're looking for?

<img width="785" alt="Screenshot 2022-12-19 at 11 49 55 AM" src="https://user-images.githubusercontent.com/2694747/208508131-e5d7fa21-bfc3-4861-a2b7-ccb469e7f9b7.png">

<img width="731" alt="Screenshot 2022-12-19 at 11 50 21 AM" src="https://user-images.githubusercontent.com/2694747/208508203-4afb0562-cb98-4fa0-8516-e84d76b135cd.png">

<img width="166" alt="Screenshot 2022-12-19 at 11 50 39 AM" src="https://user-images.githubusercontent.com/2694747/208508261-051f248b-55cc-4752-8d78-0fad6f62e3a4.png">

**Comment by ReaderGuy42** [comment]
Yes, it does, that's perfect! I found that in the meantime but forgot to close this. Thank you so much for adding the LaTeX functions!!
