### ISSUE TITLE
How to add today's date to output path?

### ISSUE THREAD

**Issue by DumbledoreCalrissian** [mgmeyers/obsidian-zotero-integration#141]
I would like to create a new folder with today's date ("YYYYMMDD") as the title and store the .md file inside that folder. 
I don't know how to do that. {{date}} gives me "1028152800000", I don't understand what this number indicates.

Please help!

**Comment by DumbledoreCalrissian** [comment]
I used /{{date | format("YYYY-MM-DD")}}/ and it worked. :)

**Comment by DumbledoreCalrissian** [comment]
My bad, that was the date of the article. 
How do I add today's date?

**Comment by bartosz-mccormick** [comment]
There's several "date" variables you can access:
- accessDate
- Date
- dateAdded
- dateModified
- ...

You can take a look yourself using the plugin's "Data explorer"

Maybe this one will work well for you: `{{importDate| format("YYYY-MM-DD")}}`

Here's how I have implemented my output path: `Zettelkasten/zotero/{{importDate| format("YYYY-MM-DD")}} {{citekey}}.md`

**Comment by DumbledoreCalrissian** [comment]
Thank you :)
