### ISSUE TITLE
Breaking update of better BibTeX

### ISSUE THREAD

**Issue by mscott99** [mgmeyers/obsidian-zotero-integration#144]
I updated better BibTeX and the error "Cannot read properties of undefined (reading '2')" and "Cannot read properties of undefined (reading 'undefined')"

I believe this is due to the update of better BibTeX because I had it fail on one computer, and only when updating the better BibTeX for the second computer. I will try to bring better BibTeX to an older version again.

<img width="683" alt="Screenshot 2022-12-18 at 10 27 13 PM" src="https://user-images.githubusercontent.com/15056843/208361954-99631532-940d-4648-bf8b-bc82d5bc0396.png">

**Comment by mscott99** [comment]
I downgraded betterbibtex to 6.7.42 (instead of the new 6.7.43) and now it works again.

**Comment by ss52** [comment]
I have the same issue. I'm just tried to set up an integration and used the last version of a betterbibtex.

**Comment by bnlawrence** [comment]
I have the same issue, also fixed by regressing better bibtex to 6.7.42 and turning off automatic updates.

**Comment by mgmeyers** [comment]
I figured out what was going on after the update and added a fix. Please update and let me know if you still encounter any issues.

**Comment by kfitz** [comment]
I was running into this as well and the update fixes the bibtex errors, but now cite keys are coming in empty, so my notes, set to  "notes/{{cite key}}.md" are all appearing as "@" with nothing further.
