### ISSUE TITLE
Update due to better BibTeX break produces empty cite keys 

### ISSUE THREAD

**Issue by kfitz** [mgmeyers/obsidian-zotero-integration#145]
Just left this on #144, though the issue closed: 

> I was running into this as well and the update fixes the bibtex errors, but now cite keys are coming in empty, so my notes, set to  "notes/{{cite key}}.md" are all appearing as "@" with nothing further.

_Originally posted by @kfitz in https://github.com/mgmeyers/obsidian-zotero-integration/issues/144#issuecomment-1358088369_

**Comment by mgmeyers** [comment]
@kfitz Just to check, which version of this plugin are you on? I noticed this, too, and thought I fixed it in version 2.2.33

**Comment by kfitz** [comment]
Ahhh, when I updated it went to 2.2.32 -- now I've updated to 2.2.33 and all is well!

**Comment by retorquere** [comment]
@mgmeyers what changed that broke the integration? I didn't change anything about the json-rpc interface in the new version.

**Comment by retorquere** [comment]
Oh I see, sorry about that. `citationKey` is going to be the formal field when Zotero adds their own.

**Comment by mgmeyers** [comment]
Ah, good to know! Was an easy update on my end, so no worries.
