### ISSUE TITLE
Cannot import from Zotero

### ISSUE THREAD

**Issue by wesbz** [mgmeyers/obsidian-zotero-integration#152]
I couldn't find a similar issue to mine.
I installed Better BibTex and the plugin on Obsidian. However, when I try to import from zotero I get the following error
![image](https://user-images.githubusercontent.com/5843554/209374830-f701f2b3-00c0-452c-ad0a-7362ba9e341d.png)
Could you please help me solve that?
Thanks in advance

**Comment by cdmcdermott** [comment]
Same. Was working fine when i last used it a few days ago. Has something changed?

**Comment by iyzg** [comment]
<img width="342" alt="image" src="https://user-images.githubusercontent.com/32868356/209402601-c2887e96-d37f-4075-9d2d-6d03c9f77726.png">

Same issue here

**Comment by iyzg** [comment]
Hey, I just noticed that I missed an update which fixed this issue. I think that might be what's going wrong for you guys as well :)

Hope that helps!

**Comment by cdmcdermott** [comment]
@iyzg was that an update for Obsidian or Zotero? I am on latest version of both as far as i know - Obsidian v1.1.9 and Zotero 6.0.18

**Comment by sammylvp** [comment]
@cdmcdermott , I found better bitex was updated to 6.4 automatically and then the error started to appear. When I downgraded better bitex to 6.2 it worked again. There might be modifications from obsidian side needed.

**Comment by mgmeyers** [comment]
Hi all, please make sure Zotero Integration is up to date (2.2.34). The latest release fixed some issues with the newest version of better bibtex

**Comment by wesbz** [comment]
I tried installing the plugin again (2.2.34). Still encountering the exact same issue. I selected "Better BibLaTeX" as Item Format in the Quick Copy settings. Could it be the cause?

**Comment by cdmcdermott** [comment]
Updating Zotero Integration in Obsidian fixed it for me, thanks

**Comment by rokkokoro** [comment]
I had the same Issue, now after the update of Zotero integration it shows this instead: 
<img width="316" alt="Screenshot 2023-02-04 at 11 35 28" src="https://user-images.githubusercontent.com/124386957/216762331-9930beac-ac23-4a7c-bfc7-6392ad230ee2.png">
can someone help?

**Comment by domiden** [comment]
> I had the same Issue, now after the update of Zotero integration it shows this instead: <img alt="Screenshot 2023-02-04 at 11 35 28" width="316" src="https://user-images.githubusercontent.com/124386957/216762331-9930beac-ac23-4a7c-bfc7-6392ad230ee2.png"> 
> can someone help?

@rokkokoro Perhaps, that work-around might help: https://github.com/mgmeyers/obsidian-zotero-integration/issues/172#issuecomment-1409425265
