### ISSUE TITLE
Possible to make the grey overlay when the Zotero picker is active a little less grey/make the Obsidian note more visible?

### ISSUE THREAD

**Issue by ReaderGuy42** [mgmeyers/obsidian-zotero-integration#154]
Would it be possible to make the overlay that appears when the Zotero picker is active less prominent, so it's easier to see the regular text of the Obsidian note? and is it possible to change the position of that picker on the screen more to the top of the screen, so the active line in the note is visible?

Not sure if either of these are dictated by Zotero itself, if so you might not be able to influence that.
Just curious?
Thanks!

**Comment by mgmeyers** [comment]
Unfortunately I do not have much control here! Zotero and obsidian dictate the overlays.
