### ISSUE TITLE
Plugin fails to load when clicking on "enable" in install window

### ISSUE THREAD

**Issue by mihock** [mgmeyers/obsidian-zotero-integration#16]
Hello,

My Obsidian version is 0.14.2.

Best
Michael

**Comment by mbarritt** [comment]
Hi,

Same for me, Zotero Desktop Connector plugin fails to load. I have Obsidian 0.14.3 installed. 

Ah...I think I see the problem. I have Obsidian 0.14.3 installed, but in the About screen the "installer version" is 0.12.19. I've been using the built in "check for updates" mechanism to update for quite some time. 

I've just downloaded a fresh install of Obsidian and replaced the old version in the Applications folder (now it lists the installer as 0.14.2 and the Obsidian version as 0.14.3) and now the Zotero plugin does load. 

Hopefully this distinction helps the OP and others.

Matthew

**Comment by mihock** [comment]
@mbarritt 

Now it works, thank you very much. Didn't know that the "installer version" is different from the Obsidian version. Also thanks for the nice plugin!

Best 
Michael

**Comment by rshorst** [comment]
This is happening for me as well. It shows up as a plugin but fails to load. I have installer version 1.0.0

Thanks in advance

**Comment by mgmeyers** [comment]
@rshorst Do you see any errors in Obsidians developer console? You can open it by pressing cmd/ctrl + shift + i

**Comment by rshorst** [comment]
Wow! That was fast! This is what I'm seeing:

app.js:1 Plugin failure: obsidian-zotero-desktop-connector Error: ENOENT: no such file or directory, open '/Users/rachelhorst/Desktop/obsidian-student-starter-vault-main/.obsidian/plugins/obsidian-zotero-integration-main/main.js'
(anonymous) @ app.js:1

DevTools failed to load source map: Could not load content for app://obsidian.md/luxon.js.map: System error: net::ERR_FILE_NOT_FOUND

**Comment by rshorst** [comment]
(Apologies if I am making some really stupid and obvious mistake)
