### ISSUE TITLE
All Annotations are duplicated into Obsidian from a pdf edited in the Zotero pdf Editor

### ISSUE THREAD

**Issue by Jeff-JAG** [mgmeyers/obsidian-zotero-integration#161]
After editing a pdf using the built-in pdf editor, Zotero Integration writes all pdf Annotations twice into the Obsidian md note.  I did not notice this behavior when using the Adobe Acrobat Reader.  It began after I started using the built-in Zotero pdf editor.

Here's what I did:
1.  Edited a pdf using the built-in Zotero pdf editor.
2.  Saved the pdf file back to the folder where it came from.
3. Ran the Zotero Integration: Import Notes function in Obsidian on the Zotero item.
4. All Annotations were entered into the Obsidian md note twice.
5. Each Annotation entry had a different "annotation ID"
6. Both annotation IDs would go to the same annotation (e.g. highlighted text) in the pdf.

How do I eliminate the duplicated entries?

**Comment by mgmeyers** [comment]
@Jeff-JAG This is likely because annotations are now coming in from both zotero and the PDF itself.

You can see where they come from in the data explorer:

<img width="719" alt="Screenshot 2023-01-10 at 6 34 52 PM" src="https://user-images.githubusercontent.com/2694747/211704852-7c491266-261c-4c15-ad56-645e809e935d.png">

You can get the annotations that only belong to the PDF like so: `{% set annotations = annotations | filterby("source", "startswith", "pdf") -%}`

See https://github.com/mgmeyers/obsidian-zotero-integration/issues/128 and https://github.com/mgmeyers/obsidian-zotero-integration/issues/92 for more details.

**Comment by Jeff-JAG** [comment]
Thanks for the speedy response!

I was able to filter using your suggested selection criterion in my template.  I then changed it to read filterby("source", "startswith", "zotero"), and I still came up with doubled annotations (!?).

So I looked at the Data Explorer and discovered that there were three entries for each annotation.  First came a list with source="zotero" that had two entries for each annotation with unique IDs, then a list followed that listed each annotation once with source="pdf" giving a total of three entries for each annotation.  Below is an extract from the Data Explorer for the pdf.

Any idea about why the "zotero" notes are being doubled?

=================================
0 {} 12 keys
annotatedText"A Zettelkasten is a personal tool for thinking and writing."
color"#ffd400"
colorCategory"Yellow"
datemoment(Tue Jan 10 2023 17:52:37 GMT-0500)
id"PCK8ZGSR"
page3
pageLabel"3"
source"zotero"
type"highlight"
x82.2
y628.339

1 {} 12 keys
annotatedText"A Zettelkasten is a personal tool for thinking and writing."
color"#ffd400"
colorCategory"Yellow"
datemoment(Tue Jan 10 2023 19:39:43 GMT-0500)
id"BVGNV3SE"
page3
pageLabel"3"
source"zotero"
type"highlight"
x82.2
y628.339

262 {} 12 keys
annotatedText"A Zettelkasten is a personal tool for thinking and writing."
color"#ffd400"
colorCategory"Yellow"
datemoment(Tue Jan 10 2023 22:52:37 GMT-0500)
id"highlight-p3x82y628"
page3
pageLabel"3"
source"pdf"
type"highlight"
x82.2
y628.34

**Comment by Jeff-JAG** [comment]
Additional investigation:

I format my Obsidian entries with the annotation ID as, e.g.
 [Page 4](zotero://open-pdf/library/items/8BC5P6M4?page=4&annotation=XABHIY5M)

When I filter for the pdf annotations, the link will only go to the page the annotation is on.

When I filter for the zotero annotations, although doubled, both (!?) will go directly to the annotation.

**Comment by Jeff-JAG** [comment]
@mgmeyers - I'm going to close this.  It seems the problem is a limitation in trying to use the built-in pdf reader/marker and an external pdf reader/marker.  

Further reading on this shows that importing and exporting the annotations to be able to access them in both readers results in the duplicated entries.  Importing annotations made in the external reader will import as locked.  Then saving the pdf file from Zotero will add the annotations from the Zotero database.  Repeating this a couple of times got me my triple references.

It isn't your error.  Your plugin is just picking up what Zotero has put there (multiple times in my case!).
