### ISSUE TITLE
filterby with lastExportDate/lastImportDate on zotero-entries without a linked pdf seems not to work

### ISSUE THREAD

**Issue by Git-Tobias** [mgmeyers/obsidian-zotero-integration#162]
Import only the notes from a literature entry without a linked pdf-file dont work with filterby("dateModified", "dateafter", lastImportDate).

The template code (the parameter "lastExportDate" does not work as well)
```
{% persist "notes" %}
{% set newNotes = notes | filterby("dateModified", "dateafter", lastImportDate) %}
{% if newNotes.length > 0 %}

{% for note in newNotes %}
{{note.note}}
{% endfor %}

{% endif %}
{% endpersist %}
```
imports the note from the zotero entry
![image](https://user-images.githubusercontent.com/56408951/211945110-107b538c-2110-43db-87bd-e5f03854171e.png)

but not the note from this zotero entry
![image](https://user-images.githubusercontent.com/56408951/211945289-e5a57a8a-9b00-4faa-b5dd-a671d2ae2815.png)

It looks like its because the missing annotationable pdf from the zotero entry above.

![image](https://user-images.githubusercontent.com/56408951/211946251-3528da09-d069-43c0-ae5a-d719fd8b04c9.png)
![image](https://user-images.githubusercontent.com/56408951/211946275-8aedc1c2-4c98-44a2-90f8-797c6509e6ef.png)

**Comment by mgmeyers** [comment]
@Git-Tobias I found the bug that was causing this. Please update the plugin and try again.
