### ISSUE TITLE
When "Insert notes into current document", "Go to annotation" appears in the front of highlighted text

### ISSUE THREAD

**Issue by vanish87** [mgmeyers/obsidian-zotero-integration#164]
When "Insert notes into current document", "Go to annotation" appears in the front of highlight text
![image](https://user-images.githubusercontent.com/1934796/212550897-af3d988e-32ee-488d-9a6c-57b45cdd8c1d.png)

It is possible to make it after the highlight text? Like this
![image](https://user-images.githubusercontent.com/1934796/212550904-b6e7d96a-92e1-4d75-8408-23122633a1b2.png)

Or having options/formats for this

**Comment by mKobrow** [comment]
Hey, I stumbled across this while searching for a solution to change the formatting. As there is no "official" one you could manually change the appearance by changing those lines:

https://github.com/mgmeyers/obsidian-zotero-integration/blob/5693ab27316278e11c5f10b6fc0d3501ebedc07a/src/bbt/exportNotes.ts#L22-L32

For your whish it would have to be something like:

```js
 annot.insertAdjacentElement( 
   'afterend', 
   createEl('a', { 
     text: '(pdf)', 
     href: `zotero://open-pdf/library/items/${attachmentKey}?page=${json.pageLabel}&annotation=${json.annotationKey}`, 
   }) 
 ); 
 annot.insertAdjacentElement( 
   'afterend', 
   createSpan({ text: ' ' }) 
 );
```

**Comment by mgmeyers** [comment]
@vanish87 No, this is currently not possible using the default templates. I would recommend creating an import format if you want any customization.
