### ISSUE TITLE
Add author information to template

### ISSUE THREAD

**Issue by Sciemon** [mgmeyers/obsidian-zotero-integration#165]
I feel like this is a very stupid question but when I use the Zotero Data Explorer in Obsidian to check the data I see that there are all sorts of information (about annotations etc.) but not for example the author(s) of the selected item. 
How do I add the author in my template, which looks like this at the moment (not so important): 

{% persist "annotations" %}

### Annototations imported on [[{{importDate | format("YYYY-MM-DD")}}]]

{% if annotations.length > 0 -%}

{% for annotation in annotations %}{% if annotation.annotatedText %}
<span style="color: {{annotation.color}};">&#9632;</span> "{{annotation.annotatedText}}" ([p. {{annotation.page}}](zotero://open-pdf/library/items/{{annotation.attachment.itemKey}}?page={{annotation.page}}&annotation={{annotation.id}}))
{% elif  annotation.imageRelativePath %}
<span style="color: {{annotation.color}};">&#9632;</span> ![[{{annotation.imageRelativePath}}]]
{%- endif %}
{% if annotation.comment %}- [b] {{annotation.comment}}
{% endif %}{% endfor %}{% endif -%}

{% endpersist %}

**Comment by Yaozhuwa** [comment]
- Author: {% for t in creators %}{{t.firstName}}{{t.lastName}}{{t.name}}{% if not loop.last %}, {% endif %}{% endfor %}

**Comment by Sciemon** [comment]
Thanks a lot 👍  I tried "creators" but I tested it with an item that had no authors and got confused :)
