### ISSUE TITLE
error converting formatted bibliography to markdown

### ISSUE THREAD

**Issue by WildOsk** [mgmeyers/obsidian-zotero-integration#17]
I am trying to add  cite and Bibliography but i cant add Bibliography i was wondering if somebody can help me

this is my **file**:

![image](https://user-images.githubusercontent.com/62115925/160949113-b6e7efb3-7ce9-4379-9bbc-b4985b5888bb.png)

error image:
![image](https://user-images.githubusercontent.com/62115925/160949039-b5e89c8a-38a0-4097-baad-3f6959780ac7.png)
config:

![image](https://user-images.githubusercontent.com/62115925/160949082-30ee0a85-2d25-434f-adce-b501ce2c97a1.png)

Thanks.

**Comment by mgmeyers** [comment]
Hmm, this looks related to #9. 

What happens when you copy the bibliography directly from Zotero?

<img width="362" alt="Screen Shot 2022-03-30 at 7 01 17 PM" src="https://user-images.githubusercontent.com/2694747/160961298-537ce430-0277-49b3-bcdb-f65b8e1b1ad0.png">

**Comment by WildOsk** [comment]
output copy bibliography: Delphinidae. (2022). En Wikipedia, la enciclopedia libre. https://es.wikipedia.org/w/index.php?title=Delphinidae&oldid=142605514
now I had the option i restarted it
![image](https://user-images.githubusercontent.com/62115925/161092568-6bfa84fb-91b4-46ce-9f34-9484b2da4f49.png)

**Comment by WildOsk** [comment]
Yeah, ok thanks I will be checking #9 and how it ends

**Comment by mgmeyers** [comment]
I just made an update that should fix this if you define the bibliography style within the plugin settings. For example:

<img width="770" alt="Screen Shot 2022-04-05 at 12 46 53 PM" src="https://user-images.githubusercontent.com/2694747/161837261-d4a9f7e7-6076-4959-a2ba-a7f90b3151cd.png">

Let me know if this fixes things for you.
