### ISSUE TITLE
cannot read properties of undefined (reading '2')

### ISSUE THREAD

**Issue by yin-ori** [mgmeyers/obsidian-zotero-integration#170]
Hello everyone

I've installed the plugin and tried to import notes with a template different from the standard import format (which does work). I've tried several templates that are all supposed to be working just in case, but will always end up with the error above. 

I've read somewhere else it might be other plugins conflicting, but even after disabling everything else, the error pops up. 

This would be a crucial factor for me to decide whether I'm sticking with obsidian or move back to Zettlr. 

Does anybody have any idea why this pops up? (Although I don't think I've set up anything weird in zotero I'd be fine with sharing my library too if that helps reproducing the error)

Thank you!

**Comment by mgmeyers** [comment]
@yin-ori Try updating the plugin to version 2.3.0 and let me know if you still run into this issue

**Comment by wenlzhang** [comment]
I am having the same issue. I have updated to version 2.3.1 and re-started Obsidian, and the issue is the same.

**Comment by yin-ori** [comment]
it does work now! thank you!
