### ISSUE TITLE
2.3.2 Isn't working anymore - KEYSCOPE IS GLOBAL

### ISSUE THREAD

**Issue by ClusterWood** [mgmeyers/obsidian-zotero-integration#172]
Obsidian 1.1.9, ZDC 2.3.2
![image](https://user-images.githubusercontent.com/104789621/215415114-93f13b1a-101b-4be0-98c4-abe4735cd970.png)

"Error retrieving item data: keyscope is global, do not provide a library ID"
Last working version here is ZDC 2.2.35

**Comment by wenlzhang** [comment]
I am having the same issue with 2.3.2 and Obsidian 1.1.12.

**Comment by tom-mclean** [comment]
And me, 2.3.2, Obsidian 1.1.9, Zotero 6.0.20.

Import seemed to be hanging before I updated to 2.3.2, but no error message was showing then, so tried updating. Now the same error message as @ClusterWood

**Comment by pnlawlor** [comment]
Same issue. There is a similar-appearing bug here:
https://github.com/retorquere/zotero-better-bibtex/issues/2014
Where the issue seemed to be an issue with BetterBibTex.

**Comment by mgmeyers** [comment]
Working on a fix for this: https://github.com/retorquere/zotero-better-bibtex/pull/2394

One way you can get around this for now is by setting `Keep keys unique` to `within each library`:

<img width="706" alt="Screenshot 2023-01-30 at 2 06 41 PM" src="https://user-images.githubusercontent.com/2694747/215606443-c692671a-f313-4c32-8ea9-4e7d92859437.png">

I know this isn't ideal for some of you. I'll try and get this sorted ASAP

**Comment by mgmeyers** [comment]
Just an update: this will be fixed once the next version of Better Bibtex is released

**Comment by RobertTalbert** [comment]
It appears that Better Bibtex has been updated (Zotero says Last Updated February 4, 2023) but I am still getting this error message.

**Comment by mgmeyers** [comment]
@RobertTalbert Unfortunately, the version of Better Bibtex with a fix for this issue has not yet been released. The current version is v6.7.54 which was released on January 27th (https://github.com/retorquere/zotero-better-bibtex/releases)

**Comment by mgmeyers** [comment]
@ClusterWood & everyone else, try updating the better bibtex plugin (and zotero integration) and see if this issue is now fixed for you

**Comment by ClusterWood** [comment]
Zotero 6.0.22; BBT 6.7.55; ZI 2.3.4
Works perfect for me.
Many thanks!
