### ISSUE TITLE
Annotations are not imported from items in Group Libraries

### ISSUE THREAD

**Issue by willismonroe** [mgmeyers/obsidian-zotero-integration#174]
I'm not sure if this is a known limitation, but I ran into this today. I was trying to import annotations from a PDF attached to a reference in a "Group" that I belong to. The note was being created with all of the citation information filled out, but the annotations were not coming through. After I copied the record to "My Library" the import worked just fine.

**Comment by willismonroe** [comment]
I just saw #122 but I'm running 2.3.2 and still seeing this issue.

**Comment by mgmeyers** [comment]
@willismonroe Try updating the better bibtex plugin (and zotero integration) and see if this issue is fixed for you

**Comment by willismonroe** [comment]
Thanks for the prompt @mgmeyers, I can confirm this is now fixed.

**Comment by MesmerV** [comment]
Hi there, thanks for the great work on this !
I'm bumping into the same issue, and can't import annotations from papers that I dragged from a Group Library :/ 
steps I followed:
 - Imported Group LIbrary, Drag and drop refs to My Library
 - Auto Found and download pdfs for those refs
 - annotate one
 - Try to import in Obsidian
 
 Looking into the logs it seems that zotero is still trying to grasp things from the group library.. can't figure out what is happening.. 
X-Zotero-Version: 6.0.36
X-Zotero-Connector-API-Version: 2
BetterBibteX zotero-better-bibtex-6.7.169
 
does anyone know how to solve this issue ?
