### ISSUE TITLE
Error retrieving item data: keyscope is global, do not provide a library ID

### ISSUE THREAD

**Issue by ChloeZhou1997** [mgmeyers/obsidian-zotero-integration#178]
My obsidian zotero-integration used to work fine, but today when I tried to import articles that I put into library, I received the following error message:

Error retrieving item data: keyscope is global, do not provide a library ID

I tried to search online what it mean but can't find any relevant information.

---

update: the default import note is still working, it's only when importing with the self-customized format that doesn't work. I tried an empty template, it's not working either so I don't think it's the problem with the template itself.

**Comment by mgmeyers** [comment]
This is a known issue and will be fixed when the next version of better bibtex is released. See #172 for a temporary work around
