### ISSUE TITLE
import requires a pdf as an attachment to export the notes attached to a Zotero item

### ISSUE THREAD

**Issue by nocona71** [mgmeyers/obsidian-zotero-integration#183]
# Observed Behaviour
I created a template for [obsidian-zotero-integration](https://github.com/mgmeyers/obsidian-zotero-integration) that exports annotations _and_ notes for a zotero item (see https://github.com/nocona71/obsidian-literature-note/releases/tag/v1.0.4 )

The literature note generated by the template produces the expected output when a pdf is available in the Zotero item:
![grafik](https://user-images.githubusercontent.com/63201084/219852622-dd4990db-09eb-4f3b-9b8e-bb1a046a2347.png)

Result in Obsidian:
![grafik](https://user-images.githubusercontent.com/63201084/219852891-a0c597bc-5810-473b-af97-a2fd4635bafb.png)

However when I use this template with a zotero item _without_ a pdf  no notes are exported:
![grafik](https://user-images.githubusercontent.com/63201084/219852501-e0d4aa5a-1714-40b4-8927-c2f5ff3074ad.png)

Result in Obsidian:
![grafik](https://user-images.githubusercontent.com/63201084/219852902-dd56e8ad-032e-4f8b-bcc2-2ed50d512bc6.png)

# Expected behaviour
When I import a Zotero item containing notes but no pdf the notes shall be exported.

**Comment by mgmeyers** [comment]
@nocona71 Do you encounter any errors in the developer console (command/ctrl + shift + i) when you run your import? I can't seem to reproduce this issue. Do the notes come through in the Data Explorer when you inspect this item without a PDF?

**Comment by nocona71** [comment]
@mgmeyers Thanks for putting in the effort to retest the issue. 

regarding your questions:

> Do you encounter any errors in the developer console (command/ctrl + shift + i) when you run your import? 

No, I just retested in an empty vault containing just this plugin and the obsidian-literature-template + CSS snippet
![grafik](https://user-images.githubusercontent.com/63201084/221970150-ceb93733-c35d-4ec5-a3b1-c3833d6e7724.png)

> Do the notes come through in the Data Explorer when you inspect this item without a PDF?

Yes. I can see them in the graph of the Zotero data explorer (#1 and #2). However not in the corresponding MD generated by the obsidian-literature-template + CSS snippet (#3)
![obsidian annotated](https://user-images.githubusercontent.com/63201084/221971340-78d7153e-94dc-4995-94a2-2761e0100b01.png)

For reference: This is what the Zotero document looks like:

![2023-02-28 21_19_49-@TestdocumentPDF - test-lit-not-vault - Obsidian v1 1 15](https://user-images.githubusercontent.com/63201084/221971593-b2580804-7736-4640-9ce4-c95d84eb6aba.png)

**Comment by nocona71** [comment]
@mgmeyers No
![grafik](https://user-images.githubusercontent.com/63201084/221975156-56b8b29c-e313-4a7e-8fb1-af4b73aa49b1.png)

**Comment by mgmeyers** [comment]
Ok, how about if you remove ` | filterby("dateModified", "dateafter", lastImportDate)` from the note for loop?

**Comment by nocona71** [comment]
This works better.

![grafik](https://user-images.githubusercontent.com/63201084/221977788-664ca295-4b9a-4726-b174-1c3a664cb1df.png)

**Comment by mgmeyers** [comment]
Hmm, interesting. You are correct. This makes me think that something is off with the dates, though.

Could you add this to your template inside the note for loop? 

```
Import: {{lastImportDate | format()}}
Modified: {{note.dateModified | format()}}
```
Be sure to delete the existing markdown file before running the import

**Comment by nocona71** [comment]
the template:
![grafik](https://user-images.githubusercontent.com/63201084/221980109-b8a85a2e-7c0c-4780-b816-20a41b4acff7.png)

the freshly generated MD:
![grafik](https://user-images.githubusercontent.com/63201084/221980584-ffa15fc2-ad83-47dd-810f-610371b0de92.png)

**Comment by mgmeyers** [comment]
@nocona71 This was helpful. I think I tracked down and fixed the issue. Try updating the plugin and see if you can import notes now.

**Comment by nocona71** [comment]
@mgmeyers Well done, You nailed it!

![grafik](https://user-images.githubusercontent.com/63201084/221986712-fbee24fd-00e7-42b6-a8e1-d388d5f1e137.png)

fixed in: https://github.com/mgmeyers/obsidian-zotero-integration/releases/tag/2.3.4

**Comment by mgmeyers** [comment]
Great, thanks for helping me figure this out!
