### ISSUE TITLE
Is there a way to remove the "Go to annotations" link?

### ISSUE THREAD

**Issue by kandyman2017** [mgmeyers/obsidian-zotero-integration#185]
When I import notes from Zotero that I highlighted in an external PDF viewer, all the highlights are preceded by a link called "Go to annotation". This is redundant since the notes are also followed by a citation link containing the same details. The resulting 2 sets of links make the note look cluttered (see below). 

If possible, I would like to keep the citation link after the highlighted text but remove the "Go to annotation" link before it.

![go to annotation](https://user-images.githubusercontent.com/32620963/221546811-f9eb02c4-507f-4473-a99a-5e9b2d200034.jpg)

**Comment by chbroecker** [comment]
Hi @kandyman2017, could you post the template you use to import your annotations here?

**Comment by kandyman2017** [comment]
In the Zotero config editor, the string value for 'extensions.zotfile.pdfExtraction.formatAnnotationHighlight' is:
<p><blockquote> %(content) (%(cite)) </blockquote></p>

**Comment by mgmeyers** [comment]
@kandyman2017, there's no way to alter the default annotation template. You'd need to set up your own import format with a custom template.

**Comment by marbetschar** [comment]
@kandyman2017 did you manage to get rid of the "Go to annotation" link in the export? I face the same issue and kind of not being super motivated to get into the whole templating thing just for removing this one link to be honest :sweat_smile:
