### ISSUE TITLE
Error: Command was killed with SIGABRT (Aborted): .... dyld: cannot load 'pdfannots2json' (load command 0x80000033 is unknown)

### ISSUE THREAD

**Issue by gregheth** [mgmeyers/obsidian-zotero-integration#186]
This error occurred when issuing command Zotero Integration Import #1 (with template)

Issuing command Zotero Integration Import (without template) works fine.

Error: Command was killed with SIGABRT (Aborted): /Users/greg/OneDrive/2023 TEST/.obsidian/plugins/obsidian-zotero-desktop-connector/pdfannots2json /Users/greg/OneDrive/2023 TEST/Current/Note taking/Book - Not Even Trying- The Corruption of Real Science, Bruce Charlton, 2012.pdf -n image -d 120 -f jpg -o /Users/greg/OneDrive/2023 TEST/charltonNotEvenTrying2012 -q 90 --tesseract-path /opt/local/bin/tesseract
dyld: cannot load 'pdfannots2json' (load command 0x80000033 is unknown)
    at sp (plugin:obsidian-zotero-desktop-connector:113:57)
    at eval (plugin:obsidian-zotero-desktop-connector:113:5017)
    at Generator.next (<anonymous>)
    at i (plugin:obsidian-zotero-desktop-connector:6:1251)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

OCR is off.
I tried reinstalling everything including Tesseract
Tried many version of template - all failed

System is: macOS High Sierra 10.13.6 ( this is the maximum for my Macbook )
Obsidian is Version 1.1.15 (Installer 0.15.9)
> tesseract --version
tesseract 4.1.3
 leptonica-1.82.0
  libjpeg 8d (libjpeg-turbo 2.1.4) : libpng 1.6.39 : libtiff 4.5.0 : zlib 1.2.13 : libwebp 1.3.0 : libopenjp2 2.5.0
 Found AVX
 Found SSE
 Found libarchive 3.6.2 zlib/1.2.13 liblzma/5.2.9 bz2lib/1.0.8 liblz4/1.9.4 libzstd/1.5.2

>  go version
go version go1.20.1 darwin/amd64

I suspect I need to recompile pdfannots2json on my macbook

**Comment by mgmeyers** [comment]
@gregheth I see your vault is in one drive, is it synced with another device?

**Comment by gregheth** [comment]
thanks for replying! I appreciate your work.
I will create a new Obsidian vault outside OneDrive and not sync'ed by Obsidian.  Then reinstall and test.
And can I try recompiling pdfannots2json?  Can you tell how to do this?

**Comment by mgmeyers** [comment]
@gregheth Hmm, the easiest way to compile would be to install it via homebrew `brew install mgmeyers/pdfannots2json/pdfannots2json`. Then you could copy the executable over into the plugin directory

**Comment by gregheth** [comment]
Within this Obsidian vault
 - Only this plugin installed
 - No OneDrive
 - No Obsidian sync

Zotero is linked to pdf's within OneDrive.

Tested as above.
- `Zotero Integration Import` (without template) works fine.
- `Zotero Integration Import #1` (with template) fails with the same error as follows:

>Error: Command was killed with SIGABRT (Aborted): /Users/greg/2023-02-Obsidian-test/.obsidian/plugins/obsidian-zotero-desktop-connector/pdfannots2json /Users/greg/OneDrive/2023 TEST/Current/Note taking/Book - Not Even Trying- The Corruption of Real Science, Bruce Charlton, 2012 (PDFDrive).pdf -n image -d 120 -f jpg -o /Users/greg/2023-02-Obsidian-test/charltonNotEvenTrying2012 -q 90 --tesseract-path /opt/local/bin/tesseract
dyld: cannot load 'pdfannots2json' (load command 0x80000033 is unknown)
    at sp (plugin:obsidian-zotero-desktop-connector:113:57)
    at eval (plugin:obsidian-zotero-desktop-connector:113:5017)
    at Generator.next (<anonymous>)
    at i (plugin:obsidian-zotero-desktop-connector:6:1251)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)


Here is a screen-shot of Obsidian console:
![Screen Shot 2023-03-01 at 10 02 06 am](https://user-images.githubusercontent.com/216906/222002412-349c2aec-d246-4cb6-b3e7-cf4d1ce5c4a6.png)

**Comment by gregheth** [comment]
I have needed to use MacPorts because Homebrew continually tries to update `freetype` to a version that will not compile on my macbook.  And because I have `pinned` `freetype` Homebrew will not allow me to compile `pdfannots2json`

I have Ruby and Go installed.   Without it being too much trouble, can you provide me with instructions on how to compile `pdfannots2json` outside Homebrew?

**Comment by gregheth** [comment]
Let me know.  I need to find an alternative Obsidian plugin.  I will understand

**Comment by mgmeyers** [comment]
@gregheth You would need to clone this repo: https://github.com/mgmeyers/pdfannots2json

Then, in that directory you would run

```
go build -o pdfannots2json .
```

**Comment by gregheth** [comment]
thank you. Much easier that I expected.  Sorry - I should have been able to work that out myself

**Comment by gregheth** [comment]
That worked!  Thank you very much. I have bought you a few coffees
