### ISSUE TITLE
Error when extracting notes/annotations from Zotero to Obsidian

### ISSUE THREAD

**Issue by nomadphase** [mgmeyers/obsidian-zotero-integration#188]
Hi Matthew,

I've searched the outstanding issues and couldn't see one like mine.

The issue is that when I attempt to import notes/annotations from Zotero to Obsidian, there is an error in converting the document to markdown. It notes that the mode must be in bibliography, not export. 

I know it's probably something simple, but I couldn't see much about this issue online elsewhere.

Cheers,
Peter

![image](https://user-images.githubusercontent.com/72380765/222032074-0099b2ea-dc18-4d5d-9c5e-fc03feb40211.png)

**Comment by mgmeyers** [comment]
@nomadphase Could you update to the latest version of better bibtex and verify this is still an issue?

**Comment by RobertTalbert** [comment]
I have the latest Better Bibtex (it says it was updated today, March 9, 2023) and I am getting this same error. Specifically

>Error converting formatted bibliography to markdown: Error: mode must be bibliograpy, not export

FWIW that misspelling of "bibliography" is in the error message. 

The plugin is successfully creating a note, but after putting in the front matter, there's nothing else. Here for example is an Obsidian note created using the plugin, but there are a lot of highlighted sections in the original that aren't getting pulled in: 

<img width="837" alt="FreemanEtAl_2014_-_RT_Notes_-_Obsidian_v1_1_16" src="https://user-images.githubusercontent.com/3129186/224046391-a551ac87-e353-40e9-b098-f7c2a02bade8.png">

Running Obsidian 1.1.16 and the plugin was freshly installed before trying this out.

**Comment by nomadphase** [comment]
Hi Matthew,

This issue is now resolved. Not sure what exactly fixed it
