### ISSUE TITLE
Literature note template - {{bibliography}} not working anymore ?

### ISSUE THREAD

**Issue by ObliviousMonkey** [mgmeyers/obsidian-zotero-integration#189]
Hi,

As a disclaimer, I'm quite new to Obsidian and Zotero Integration.

I had managed to put together a template for the creation of Literature Notes. In the plugin settings, I had correctly pointed the plugin to this template, filled a Bibliography Style and double checking that it was indeed installed with Zotero, and everything was happening as it should.

For example this template has sections like this:

```
> [!LINK] Link to pdf
> {%- for attachment in attachments | filterby("path", "endswith", ".pdf") %}  
>  [{{attachment.title | replace("_", " ")}}](file:///{{attachment.path | replace(" ", "%20")}})  {%- endfor %}
```

![image](https://user-images.githubusercontent.com/43589586/222393862-74caacf3-23fb-4088-92ab-87e0527d9536.png)

That correctly create a functional direct link to open the pdf file.

But I also had the following section to create a "Cite" callout with the full bibliography of the paper:

```
> [!Cite]  
> {{bibliography}}
```

And it looks like the `{{bibliography}}` doesn't point to anything anymore because even when regenerating literature notes for papers that were previously correctly rendered, this callout is now empty in the Literature Note MD:

```
> [!Cite]  
> 
```

I'm not sure where this is coming from as I know that there was an update in this plugin, but also in Zotero for instance. I don't remember where this `{{bibliography}}` came from so I have no idea _where_ the break is...

Can someone point me in the right direction ?

**Comment by ScholzDaniel** [comment]
Not exactly sure where this is coming from since it works for me. You might look into the Zotero Preferences under Export and change the quick copy settings.
Additionally, you can check inside Obsidian with the help of the command "Zotero Integration: Data explorer" if the bibliography entry is really empty when you use the given template.

**Comment by CarolineP-DS** [comment]
Thanks for investigating @ScholzDaniel !

I had never checked the Data explorer, I now see how to customize my template even further!

The `bibliography` entry is indeed empty (`""`), even though the bibliography style in Zotero Integration and in Zotero Export settings is the same. And the style _is_ installed as it's built-in (American Sociological Association 6th edition).

So the issue would be between Zotero & Zotero Integration.

I'm on Windows 11, using Zotero 6.0.22, Obsidian 1.1.16, Better BibTex for Zotero 6.7.55, Zotero Integration 2.3.4. Could you tell me which config is working for you ?

**Comment by ObliviousMonkey** [comment]
Thanks for investigating @ScholzDaniel !

I had never checked the Data explorer, I now see how to customize my template even further!

The bibliography entry is indeed empty (`""`), even though the bibliography style in Zotero Integration and in Zotero Export settings is the same. And the style is installed as it's built-in (American Sociological Association 6th edition).

So the issue would be between Zotero & Zotero Integration.

I'm on Windows 11, using Zotero 6.0.22, Obsidian 1.1.16, Better BibTex for Zotero 6.7.55, Zotero Integration 2.3.4. Could you tell me which config is working for you ?

**Comment by ScholzDaniel** [comment]
Just to clarify: I am not an expert with the zotero integration and am also just starting with it.
I'm on Windows 10, using Zotero 6.0.19, Obsidian 1.1.15, Better BibTex for Zotero 6.7.54, Zotero Integration 2.3.2.
Seems like you are ahead of me with every single version, feeling old. :)

**Comment by mgmeyers** [comment]
@ObliviousMonkey Could you update to the latest version of better bibtex and verify this is still an issue?

**Comment by ObliviousMonkey** [comment]
I actually have the exact same problem on macOS 13.2.1 with Zotero 6.0.22, Obsidian 1.1.16, Better BibTex for Zotero 6.7.57, Zotero Integration 2.3.4.

However I finally noticed that the issue I have seems to be specific to items contained in group libraries, which is what I'm working with now. I do have a main library of 3k+ items that seems to be unaffected : the `bibliography` field in the Data explorer is correctly populated for every item I've randomly tested.

Noting again that it was working fine until a few days ago for these group libraries items.

**Comment by mgmeyers** [comment]
Thanks @ObliviousMonkey, that narrowed it down for me. Try updating this plugin to 2.3.6 and see if the bibliography shows up for you

**Comment by ObliviousMonkey** [comment]
Thanks for the very quick fix @mgmeyers, I can confirm that it's a perfect fix on macOS, and I expect it will be the same on Windows (I'll be able to check on Monday).
