### ISSUE TITLE
I wonder why you don’t solve the problem that the picture does not display when the Zotero notes are imported into Obsidian

### ISSUE THREAD

**Issue by luohuaaa** [mgmeyers/obsidian-zotero-integration#192]

**Comment by luohuaaa** [comment]
I CANT BELIEVE IT

**Comment by Lusenc** [comment]
I have the same question.

**Comment by Solarrixs** [comment]
Please be more specific, what's the problem? How can one replicate it?

I don't have this issue.

**Comment by mgmeyers** [comment]
Images will now be imported when using the "Import notes" or "Insert notes into current document" commands
