### ISSUE TITLE
Template variables: are desktopURI and pdfZoteroLink incorrect for group library items?

### ISSUE THREAD

**Issue by fpopineau** [mgmeyers/obsidian-zotero-integration#194]
For a group library item, I get:
```
desktopURI     "zotero://select/library/items/QDBF9PW2"
pdfZoteroLink  "[Full Text PDF](zotero://select/library/items/QDJGF9IW)"
select         "zotero://select/groups/2432324/items/QDBF9PW2"
```
The select link is working correctly, because it goes through the group ID.
The 2 other links do not work. Their variables should be built the same way as select.
In this case, the pdfZoteroLink should even be better:
```
pdfZoteroLink  "[Full Text PDF](zotero://open-pdf/groups/2432324/items/QDJGF9IW)"
```` 
See: https://forums.zotero.org/discussion/103096/jumping-to-link-doest-work-in-group-libararies#latest

**Comment by jeron1** [comment]
Similar to https://github.com/mgmeyers/obsidian-zotero-integration/issues/207

**Comment by mgmeyers** [comment]
This should be fixed now. Update and let me know if you encounter any issues.
