### ISSUE TITLE
Issue when I have multiple pdfs in one Zotero File

### ISSUE THREAD

**Issue by LuX1nAt0r** [mgmeyers/obsidian-zotero-integration#197]
Somehow when I have multiple pdfs in One File in Zotero the export of the annotation fails.

Like this:
![grafik](https://user-images.githubusercontent.com/66088547/224072556-ee499f4b-92a2-43e1-a57c-a3fa8fe1a4c1.png)

I only have Annotations in the first PDF which are most likely pictures. However when I run my Import template in Obsidian the Note get created and also the pictures get created but the pictures aren't inserted in the Note. When the Importing is finished I can see the pictures added to the Notes for a short period of time but than the note is empty. I already tried multiple templates with no success. The import to Obsidian works fine if there is only one PDF in a Resource File. 

Here is a picture of my template:
![grafik](https://user-images.githubusercontent.com/66088547/224073923-3372d7f1-4245-4980-9b2e-c23cc3588b43.png)

When I run the Zotero Data Explorer the Note seems to be fine but in reality the Pictures aren't added to the Note:
![grafik](https://user-images.githubusercontent.com/66088547/224074456-635bceab-1dd3-46b2-820b-d918706baf97.png)

I also tried a template which I think the Dev mentioned in an other issue which counts the Annotations and this was the result:
![grafik](https://user-images.githubusercontent.com/66088547/224074740-401ffa80-ca8e-49f1-bde4-d9002af25e84.png)
![grafik](https://user-images.githubusercontent.com/66088547/224075025-44d38974-3902-46ff-a80e-6e0393b2c25c.png)

**Comment by anton-santalov** [comment]
Faced the same problem. Solved it with writing this code (for a pleasant display of result text, you will have to remove tabs and hyphens in some places):
```
{% for attachment in attachments %}
  {% for annotation in attachment.annotations %}
    >*Quote:*
    {% if annotation.annotatedText %}
      "{{annotation.annotatedText}}"
    {% endif %}
    [{{annotation.attachment.title}}](zotero://open-pdf/library/items/{{annotation.attachment.itemKey}}?page={{annotation.page}}&annotation={{annotation.id}})
    >{% if annotation.imageRelativePath %}
      ![[{{annotation.imageRelativePath}}]]
    {% endif %}
    >*me:* 
    {% if annotation.comment %}
      "{{annotation.comment}}"
    {% endif %}
    >*Date:* 
    {% if annotation.date %}
      {{annotation.date | format("YYYY-MM-DD")}}
    {% endif %}
  {% endfor %}
{% endfor %}
```
However, I haven't found a way to determine the order in which the attached files are iterated.

**Comment by gsaltintas** [comment]
Hi, I was having the same issue, and the template by @anton-santalov helped me a lot. I want to share a slight modification that can be used to persist Annotations from multiple attachments in case it would be helpful for others in the future.

```
{% persist "annotations" %}
{# only iterate over pdf files #}
{% for attachment in attachments  | filterby("path", "endswith", ".pdf") -%}
{# directly iterating over and filtering attachment.annotations results in error in filterby clause, check if the annotations are defined #}
{%- set annot1 = attachment.annotations -%}
{% if annot1 is defined %}
{% set newAnnotations = annot1 | filterby("date", "dateafter", lastImportDate) %}
{% if newAnnotations.length > 0 %}
#### {{attachment.title}}
{% for annotation in newAnnotations  %}
<mark style="background: {{annotation.color}};"> (Page {{annotation.page}}): </mark>
{% if annotation.annotatedText -%}   
 "{{annotation.annotatedText}}" 
 {% endif -%}
{%- if annotation.imageRelativePath -%}    ![[{{annotation.imageRelativePath}}]] {%- endif -%}
{%- if annotation.comment -%}
*me:* 
    "{{annotation.comment}}" 
{%- endif -%}
{%- if annotation.allTags %} *tags:* #{{annotation.allTags | replace(", ", " #")}} {% endif -%}
{%- endfor %}
Imported: {{importDate | format("YYYY-MM-DD h:mm a")}}
{% endif %}
{% endif %}
{% endfor %}
{% endpersist %}
```
