### ISSUE TITLE
Images not imported

### ISSUE THREAD

**Issue by SaschaRoelofs** [mgmeyers/obsidian-zotero-integration#203]
Hey :)
I have the following problem:
I make my annotations (including images) in Zotero. When I am trying to import the annotations everything works fine but instead of the real images, there is just a link to the image in Zotero.
Is there a way to copy the image file?

I spent a lot of time on this. I really hope someone can help me :)

**Comment by CullumAttwell** [comment]
I am having the same issue and am commenting here so I receive replies.

**Comment by NinetLab-Redux** [comment]
I have the same issue. Images are not importing whether I import a note or I insert note into current document.
I also tried uploading an Import Template but it did not do the trick eith
[Zotero Template.md](https://github.com/mgmeyers/obsidian-zotero-integration/files/11319785/Zotero.Template.md)
er (attached here)

**Comment by mgmeyers** [comment]
Images should now be imported when using the "Import notes" or "Insert notes into current document" commands.

**Comment by NinetLab-Redux** [comment]
Thank you @mgmeyers ! I updated the plugin and works like a charm :)
