### ISSUE TITLE
Group library pdf annotations

### ISSUE THREAD

**Issue by dawasari** [mgmeyers/obsidian-zotero-integration#205]
Hi. 

Annotations in PDFs stored in group libraries aren't appearing on Obsidian. I'm using Obsidian v.1.1..16, Zotero Integration v 2.3.8, Zotero 6.0.23.

Thank you.

**Comment by jeron1** [comment]
I updated obsidian and it began working for me. (obsidian v1.2.8 (installer v.1.2.7), zotero 6.0.26, zotero integration 2.3.9, 
linux kde neon 5.27).  My (local) Library was working, but annotations from group libraries wouldn't flow into obsidian, until I updated obsidian.
