### ISSUE TITLE
The image cannot be imported again after the first import

### ISSUE THREAD

**Issue by godcreator02** [mgmeyers/obsidian-zotero-integration#219]
I'm trying the "persist" syntax as mentioned in the tutorial. Everything works perfectly when the notes are first imported from zotero to obsidian. But starting from the second time, the image files are not imported and I can just get some uncreated image links.

![image](https://user-images.githubusercontent.com/49720881/234644746-e6597a4d-b53d-484d-b3c7-7753c20dd090.png)

Here are my templates and the pdf for testing, this plugin is very nice and I hope this issue can be fixed.

Zotero version: 6.0.26
better bib tex version: 6.7.75
obsidian version: 1.1.16
the plugin is the newest version

```
## A 基本信息

==作者==： {{authors}}
==期刊==: {{publicationTitle}}
==citationkey==: {{citekey}}
{% set newAnnotations = annotations | filterby("date", "dateafter", lastImportDate) %}
新增笔记数量：{{newAnnotations.length}}
## B 可以跟进的引用

{% persist "goodcitations" %}{% if newAnnotations.length > 0 %}{% set flag = 0%}{% for annotation in newAnnotations %}{% if annotation.type == "highlight" and annotation.colorCategory == "Green"  %}{% set flag = flag + 1%}{% if flag == 1%}

### B.1 {{importDate | format("YYYY-MM-DD a h:mm")}}
{% endif %}
> [!info]
> {{annotation.annotatedText}} {{annotation.comment}} 
{% endif %}{% endfor %}{% endif %}
{% endpersist %}

## C 高亮文本

{% persist "notes" %}{% if newAnnotations.length > 0 %}{% set flag = 0%}{% for annotation in newAnnotations %}{% if annotation.type == "highlight" and (annotation.colorCategory == "Orange" or annotation.colorCategory == "Blue" or annotation.colorCategory == "Yellow") %}{% set flag = flag + 1%}{% if flag == 1%}

### C.1 {{importDate | format("YYYY-MM-DD a h:mm")}}
{% endif %}
> {{annotation.annotatedText}} {{annotation.comment}} 
{% endif %}{% endfor %}{% endif %}
{% endpersist %}

## D 高亮图片

{% persist "images" %}{% if newAnnotations.length > 0 %}{% set flag = 0%}{%for annotation in newAnnotations%}{% if annotation.imageBaseName %}{% set flag = flag + 1%}{% if flag == 1%}

### D.1 {{importDate | format("YYYY-MM-DD a h:mm")}}
{% endif %}
- ![[Attachments/Zotero/{{citekey}}/{{annotation.imageBaseName}}|300]]
{% endif %}{% endfor %}{% endif %}
{% endpersist %}
```

[Zotero_template.md](https://github.com/mgmeyers/obsidian-zotero-integration/files/11335397/Zotero_template.md)

[2023_Active Power Backflow Suppression Strategy of Cascaded PV Solid-State.pdf](https://github.com/mgmeyers/obsidian-zotero-integration/files/11335426/2023_Active.Power.Backflow.Suppression.Strategy.of.Cascaded.PV.Solid-State.pdf)

**Comment by legend053** [comment]
same issue. Btw, thanks for your template. :)

**Comment by legend053** [comment]
use this {% if annotation.imageRelativePath -%}
![[{{annotation.imageRelativePath}}]] 
{% endif -%}

**Comment by mgmeyers** [comment]
Yes, as legend053 says,`annotation.imageRelativePath` will give you the correct path to the image.
