### ISSUE TITLE
Reference inserted is blank

### ISSUE THREAD

**Issue by pbienst** [mgmeyers/obsidian-zotero-integration#22]
When I try the command to insert the citation, I can select the paper, but then the citation just reads '[1]'.

I'm using the IEEE format:

<img width="434" alt="image" src="https://user-images.githubusercontent.com/2807332/161975203-1a7a0219-9502-4237-a46a-8883fc7857bd.png">

That format is available in Zotero:

<img width="494" alt="image" src="https://user-images.githubusercontent.com/2807332/161975375-ba62d956-b905-424b-802e-2e27062e9fc6.png">

Using only Zotero, when right-clicking on an entry and choosing 'Generate bibliography from item', it puts the reference to the clipboard without problems (but without the URI of course)

**Comment by mgmeyers** [comment]
@pbienst This seems to be consistent with how zotero quick copy handles IEEE citations.

<img width="211" alt="Screen Shot 2022-04-06 at 9 21 44 AM" src="https://user-images.githubusercontent.com/2694747/162021589-cc905762-7703-4cbe-aa9b-abb8a1eef51e.png">

^ this produces: `[1]`

Did you mean to use the "Formatted Bibliography" format? That will produce the equivalent of:

<img width="211" alt="Screen Shot 2022-04-06 at 9 22 49 AM" src="https://user-images.githubusercontent.com/2694747/162021757-a4d123e2-b540-4c51-9640-fe55c45836b0.png">


> [1]P. Jakob, “Multi-stressed families, child violence and the larger system: an adaptation of the nonviolent model: Multi-stressed families and child violence,” Journal of Family Therapy, vol. 40, no. 1, pp. 25–44, Feb. 2018, doi: [10.1111/1467-6427.12133](https://doi.org/10.1111/1467-6427.12133).

**Comment by pbienst** [comment]
You're absolutely right, I got confused with citation and biography. Now a reference got inserted, but what I actually would like to insert is something that can link back to Zotero, e.g. to look at the pdf or other data:

```
[Keriven, Nicolas, Damien Garreau, and Iacopo Poli. 'NEWMA: A New Method for Scalable Model-Free Online Change-Point Detection'. ArXiv:1805.08061 {Cs, Stat}, 8 October 2018. http://arxiv.org/abs/1805.08061.](zotero://select/items/1_LZ9544KA) 
```

Is implementing this on the roadmap? It should be possible, since that's how emacs interacts with zotero through its zotxt plugin...

**Comment by mgmeyers** [comment]
You should be able to accomplish that using the `Template` output format for the citation. This allows you to pull in any of the data you see in the Data Explorer like you would with an import format template
