### ISSUE TITLE
Obsidian-Zotero plugin not pulling annotations for references with multiple PDF files

### ISSUE THREAD

**Issue by masger** [mgmeyers/obsidian-zotero-integration#221]
Hi there, I am experiencing an issue where the Obsidian-Zotero plugin is not retrieving annotations from references that contain multiple PDF files.

For instance, if a reference includes an appendix and a protocol for an RCT, the plugin does not appear to find any annotations from these files. Conversely, if I remove these additional files and only leave the article, the plugin does successfully find the annotations.

Steps to Reproduce
Ensure that a reference in Zotero has multiple PDF files associated with it, such as an appendix and a protocol for an RCT.
Create annotations in all PDF files.
Sync Zotero with Obsidian using the Obsidian-Zotero plugin.
Check for annotations in Obsidian.

**Comment by joshtownley** [comment]
Can confirm I've been experiencing the same issue, except for me the import fails with an error message in Obsidian saying 'command failed with exit code 1' ... then a bunch of file paths ... then 'no such file or directory'.

**Comment by nathancashion** [comment]
I've managed to get around this by using the [PDF Kit add-on](https://github.com/sharpevo/zotero-pdfkit) to set the file with annotations as the default PDF. However, I don't know if it would work if you want to pull annotations from both files.

**Comment by mgmeyers** [comment]
Hey all. `annotations` will only be populated with the annotations from the first PDF in a Zotero entry. You can still access annotations for other PDFs under `attachments`

<img width="495" alt="Screenshot 2023-07-02 at 3 58 43 PM" src="https://github.com/mgmeyers/obsidian-zotero-integration/assets/2694747/a0db3295-65a1-4b29-9383-589a76ddc4ad">
