### ISSUE TITLE
develop a similar plug-in for Siyuan Notes

### ISSUE THREAD

**Issue by Geo123abc** [mgmeyers/obsidian-zotero-integration#228]
[obsidian-zotero-integration](https://github.com/mgmeyers/obsidian-zotero-integration) is an amazing plugin. But Obsidian is too hard for some people. [Siyuan Notes](https://github.com/siyuan-note/siyuan) is another great note-taking or personal knowledge management software, and it introduced plug-in mechanism.

Are you interested in developing a similar plugin for Siyuan Note?  The following URL maybe useful: [plugin-sample for siyuan-note](https://github.com/siyuan-note/plugin-sample/blob/main/README.md  )

**Comment by zxhd863943427** [comment]
I think it will be great！

**Comment by Geo123abc** [comment]
[WingDr/siyuan-plugin-citation: A citation plugin for the SiYuan Note.](  https://github.com/WingDr/siyuan-plugin-citation  )
