### ISSUE TITLE
[Bug] Infinite recursion in Data explorer fields under `annotations`

### ISSUE THREAD

**Issue by MSBack** [mgmeyers/obsidian-zotero-integration#235]
There seems to be an infinite recursion in Data explorer of:
`annotations` -> `attachment` -> `annotations` -> `attachment` -> `annotations`  -> `attachment` -> `annotations` and so on.

See this gif:
![Obsidian_Qi7Pjr8CHH](https://github.com/mgmeyers/obsidian-zotero-integration/assets/33608083/e203bd6d-b7f7-48fb-ae01-0e04bab4c463)

**Comment by mgmeyers** [comment]
@MSBack this isn't really a bug, just a quirk of how the data is set up. It is indeed a circular structure, but this shouldn't be an issue. Let me know if it's causing any problems for you.
