### ISSUE TITLE
Citation insert not including italics

### ISSUE THREAD

**Issue by jwolfe99** [mgmeyers/obsidian-zotero-integration#24]
I've got everything else working, but my citations (using Chicago Manual of Style 17th edition, full note) do not come with italicized titles. I'm on a Mac (Catalina 10.15.7) and the most updated version of Obsidian and the plugin as of today (April 7, 2022).

**Comment by mgmeyers** [comment]
@jwolfe99 Currently the `Formatted Citation` option doesn't output any text formatting. With the full note style, I'd recommend using the `Formatted Bibliography` style, which _will_ give you appropriate markdown formatting
