### ISSUE TITLE
Issue: Annotations created in other PDF editors get duplicated...

### ISSUE THREAD

**Issue by olearydj** [mgmeyers/obsidian-zotero-integration#241]
Annotations created in the [Highlights app](https://highlightsapp.net/) and other standard macOS pdf tools, including Acrobat Pro, are duplicated during import.

1. Use Highlights to create a highlight and add a comment to it.
2. Import the annotations.
3. Notice that the annotation is duplicated in Data Explorer.

Sample PDF attached. Annotation appears correct in Highights, Preview, and even in Zotero's built-in PDF tool. [SparksofAGI-2023.pdf](https://github.com/mgmeyers/obsidian-zotero-integration/files/12062527/SparksofAGI-2023.pdf)

Screenshot of annotations in Data Explorer:
<img width="614" alt="image" src="https://github.com/mgmeyers/obsidian-zotero-integration/assets/42705243/e4bd1b49-5905-419e-8dd1-b22d56bb91ff">

As you can see in DE, there are two annotations created by Highlights (one for the highlight and one for the associated comment, I presume), where the built in Zotero editor only creates one.

I also tested this with comments made in Acrobat Pro (ick) and it handled them the same way as Highlights does.

Ideally these could be consolidated or easily filtered by the import template so we can use standard PDF annotations with Zotero as a ref manager.

**Comment by mgmeyers** [comment]
Hey @olearydj! So, what's going on here is that ZI is pulling both from the PDF and from Zotero. If you look at the `source` property you'll see one says `pdf` (meaning it was extracted from the PDF) and one says `zotero` (meaning it was retrieved from Zotero's database). Generally what people do in this case is filter their annotations based on their desired "source of truth"

**Comment by olearydj** [comment]
Oh, perfect. That makes sense and is easy to deal with. If pdf then use it, else zotero!

**Comment by olearydj** [comment]
Oh, perfect. That makes sense and should be easy to deal with.

**Comment by olearydj** [comment]
FWIW, I ended up adding code to detect and alert to non-pdf annotations and make it easy to track them down. Then I realized that Zotero creates copies of all externally made notes and those don't get updated until the file is opened in Zotero's editor again. Ugh. So much for me being clever and proactive. I've just gone with the following for now (whitespaced for clarity not output / syntax).

Thanks for an incredibly useful tool and wonderful way to actively procrastinate the real work of my reasearch!

```
{% if annotations | filterby("source", "contains", "pdf") | length == 0 %}
	⚠️ **No PDF annotations found.** ⚠️
{% else %}
	{% for page, annotations in annotations | groupby("page") -%}
		### Page {{ page}}:
		{% for annotation in annotations |
		  filterby("source", "contains", "pdf")%}
			#### [
			{% if annotation.color %}
				{{ annotation.colorCategory }}" "
				{{ annotation.type | capitalize }}
			{% else %}
				{{annotation.type | capitalize}}
			{% endif %}
			](zotero://open-pdf/library/items/
			  {{annotation.attachment.itemKey}}?page=
			  {{ annotation.page }}&
			  annotation={{ annotation.id }}) from PDF:
			{% if annotation.imageBaseName %}
				> ![[{{ annotation.imageBaseName }}|400]]{% endif -%}
			{% if annotation.annotatedText %}
				> {{ annotation.annotatedText }} {% endif -%}
			{% if annotation.comment %}
				*{{annotation.comment}}*
			{%- endif -%} {# annotation comment #}
		{% endfor %} {# annotation #}
	{% endfor %} {# groupby page #}
{% endif %} {# pdf annotations found #}
```
