### ISSUE TITLE
[feature request] Extracting annotations as images

### ISSUE THREAD

**Issue by carmo-lucas** [mgmeyers/obsidian-zotero-integration#247]
In my team workflow we are usually required to extract the image (i.e. screenshot) of the highlighted paragraph as well as the text.
Is there a way to achieve both extractions? Highlighted text as image **and** highlighted text as text (how it already works).

**Comment by MSBack** [comment]
Zotero doesn't store highlighted text as screenshots.

**Comment by DryIce1** [comment]
@carmo-lucas, have yo useen at the bottom of the zotero integration plugin settings there is Import Image Settings with Image OCR. Perhaps this is what you're looking for.

![image](https://github.com/mgmeyers/obsidian-zotero-integration/assets/59501376/cb8909e1-42c5-4d6d-9f52-5324271bdaee)

**Comment by mgmeyers** [comment]
Unfortunately images can only be generated from rectangle annotations, so the only way to do this would be to highlight text AND cover it with a rectangle.
