### ISSUE TITLE
Can not get a citation into obsidian

### ISSUE THREAD

**Issue by ct2034** [mgmeyers/obsidian-zotero-integration#260]
My setup just stopped working. I get the selector window from zotero just fine. But when I have selected a citation there, and press enter, nothing is entered into my note.

When use the dataexmplorer, I also get the selection window and then the explorer says "No data retrieved"

## Obsidian
```
SYSTEM INFO:
	Obsidian version: v1.3.5
	Installer version: v1.3.5
	Operating system: #85~20.04.1-Ubuntu SMP Mon Jul 17 09:42:39 UTC 2023 5.15.0-78-generic
	Login status: not logged in
	Insider build toggle: off
	Live preview: on
	Legacy editor: off
	Base theme: adapt to system
	Community theme: none
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 18
	Plugins enabled: 14
		1: Tasks v4.4.0
		2: Dataview v0.5.56
		3: Zotero Integration v3.0.7
		4: Hints Flow v1.2.0
		5: Pandoc Plugin v0.4.1
		6: Linter v1.19.1
		7: Readwise Official v2.0.1
		8: Editor Syntax Highlight v0.1.3
		9: Calendar v1.5.10
		10: Citations v0.4.5
		11: Text Extractor v0.4.6
		12: Obsidian Git v2.20.7
		13: Tracker v1.10.9
		14: Code Emitter v0.1.2

RECOMMENDATIONS:
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.
```
## Zotero
Version 6.0.26

**Comment by prashantnag93** [comment]
Same Problem It was working fine before obsidian update.

**Comment by MaxenceOuafik** [comment]
Same issue, was working just fine two days ago

**Comment by prashantnag93** [comment]
**SOLVED:** Uninstall BetterBibTex addon from Zotero. Then, download and install this version: https://github.com/retorquere/zotero-better-bibtex/releases/tag/v6.7.96 😉

**Comment by ct2034** [comment]
> **SOLVED:** Uninstall BetterBibTex addon from Zotero. Then, download and install this version: https://github.com/retorquere/zotero-better-bibtex/releases/tag/v6.7.96 wink

Can confirm. This solved it for me.

**Comment by ct2034** [comment]
I leave it to the maintainers to decide what to do with this issue. I assume they still want to update this to work with the newer better-bibtex.
