### ISSUE TITLE
BetterBibTex >v6.7.96 break this extension

### ISSUE THREAD

**Issue by ct2034** [mgmeyers/obsidian-zotero-integration#261]
> **SOLVED:** Uninstall BetterBibTex addon from Zotero. Then, download and install this version: https://github.com/retorquere/zotero-better-bibtex/releases/tag/v6.7.96 wink

Can confirm. This solved it for me.

_Originally posted by @ct2034 in https://github.com/mgmeyers/obsidian-zotero-integration/issues/260#issuecomment-1665473939_

**Comment by jeetsukumaran** [comment]
Same here. Stopped working + Data explorer reported no data available etc. Rolling back BetterBibTex restores functionality.

**Comment by woodae99** [comment]
Thanks for that! Worked for me, too

**Comment by mgmeyers** [comment]
Bug report filed: https://github.com/retorquere/zotero-better-bibtex/issues/2608

For now remain on the downgraded version.

**Comment by FChris** [comment]
Tested it with the test build 6.7.103.2608.4844 and the version 6.7.104 that was just released and it seems to be working fine again

**Comment by mgmeyers** [comment]
Can confirm that the latest version (6.7.104) fixes the issue
