### ISSUE TITLE
Defined ‘header’ template does not work

### ISSUE THREAD

**Issue by lil-i321** [mgmeyers/obsidian-zotero-integration#27]
I defined one ‘header’ template makedown file like your example in Readme file. 
But it can't work, the result just have note and annotation content , 
```
## {{title}}

### Formatted Bibliography

{{bibliography}}
{% if abstractNote %}

### Abstract

{{abstractNote}}
{% endif %}
```
The header template code does not work also.
```
{{title}}
{{abstractNote}}
```

**Comment by laurastephsmith** [comment]
Have you checked you've got the right header template file set under Settings > ZDC > Add Input Format?
