### ISSUE TITLE
Import all notes from two or more attachments for one item/article

### ISSUE THREAD

**Issue by dryezl** [mgmeyers/obsidian-zotero-integration#271]
When I tried to imported note from an article with two attachments (both pdf format), only notes from one pdf were imported, which means notes from the other pdf did not be extracted. If i delete the file already imported, and reuse obsidian-zotero-integration again. Notes from the other pdf can be imported.
I wonder how I can import notes from two or more attachments.

**Comment by dryezl** [comment]
Solutions: 
in the template for zotero integration, loop the attachments first, consider the annotations under each attachment rather than annotations under Template Data.

Helping source: 
template demo with loop attachments
https://forum.obsidian.md/t/zotero-integration-import-templates/36310/20

data field can be found in the command palette (Ctrl + P) and Zotero Integration: Data explorer

**Comment by FeralFlora** [comment]
I've also had this experience while trying to help someone implement the importing of annotations from multiple PDFs. 
Like @dryezl reports, it works with a single PDF and in the Data explorer, but it only gives me the one annotation in the first PDF, when I have more than one annotation.

Here's a Data explorer and imported note comparison:
![image](https://github.com/mgmeyers/obsidian-zotero-integration/assets/33608083/f2154868-9bdd-43ce-aab3-c6d63d9c1657)

I do get one error in the console each time I import, even though I deleted the previous literature note import and restarted Obsidian, before running a new test import: 

```
app.js:1 Uncaught (in promise) Error: File already exists.
    at t.<anonymous> (app.js:1:721243)
    at app.js:1:237258
    at Object.next (app.js:1:237363)
    at a (app.js:1:236081)
```

Here's how I import annotations from the Attachments array:
```nunjucks
{% persist "annotations" %}
{% set allAnnotations = [] -%}
{% for attachment in attachments -%}
	{% if attachment.annotations | length > 0 -%}
			{% for annotation in attachment.annotations -%}
				{% set allAnnotations = (allAnnotations.push(annotation), allAnnotations) -%}
			{% endfor -%}
	{% endif -%}
{% endfor %}
Annotations in all annotations: {{allAnnotations | length}}
{% set newAnnotations = allAnnotations | filterby("date", "dateafter", lastImportDate) -%}
Annotations in new annotations: {{newAnnotations | length }}
{% if newAnnotations.length > 0 -%}

{# RELEVANT PART ABOVE HERE, THE REST IS JUST ANNOTATION FORMATTING #}

{% for annot in newAnnotations  %}
> [!quote{% if annot.color %}|{{annot.color}}{% endif %}] {{calloutHeader(annot.type)}}
{%- if annot.annotatedText %}
> {{annot.annotatedText | nl2br}}
{%- endif -%}
{%- if annot.imageRelativePath %}
> ![[{{annot.imageRelativePath}}]]
{%- endif %}
{%- if annot.ocrText %}
> {{annot.ocrText}}
{%- endif %}
{%- if annot.comment %}
>
>> {{annot.comment | nl2br}}
{%- endif %}
>
> [Page {{annot.page}}](zotero://open-pdf/library/items/{{annot.attachment.itemKey}}?page={{annot.page}}) {{annot.date | format("YYYY-MM-DD#h:mm a")}}
{% endfor -%}
{% endif %}
{% endpersist %}
```

**Another important detail:** If I delete this line with the import date, then update the literature note, the missing annotations get added:
`%% Import Date: 2023-12-14T00:18:18.255+01:00 %%`

**Comment by FeralFlora** [comment]
This should have been addressed in https://github.com/mgmeyers/obsidian-zotero-integration/releases/tag/3.1.0

**Comment by dryezl** [comment]
Thank you for sharing the exciting news, and your code is more concise and clean than mine. 
It DOES work in version 3.1.0 and 3.1.7 
Besides, the property of pdfZoteroLink of Zotero Data Explorer may be improved to suit the situation where there are two or more pdf attachment for one item. However this would be a little hard to define the corresponding data type for this property, object or string.

the following is a demo for concatenate links to pdf files into one line 
```javascript
{%- set pdfAttachments = attachments | filterby("path", "endswith", ".pdf") %}
>pdflink:: {% for pdf in pdfAttachments %}[{{pdf.title}}]({{pdf.desktopURI}}){% if not loop.last %}; {% endif %}{% endfor %}
```
