### ISSUE TITLE
Update Notes by adding to the End, instead of overwriting the original content.

### ISSUE THREAD

**Issue by jungle-gym-ac** [mgmeyers/obsidian-zotero-integration#282]
When I re-import notes of a zotero item, the original content will be overwritten,   and some notes that I wrote manually will be LOST.

**Comment by ClusterWood** [comment]
Maybe it has something to do with this behavior? ->  update annotations #156 
mgmeyers is right: "Everything between persistence fields should persist." But outside this block I have not yet managed an update.

**Comment by yaozhenghangma** [comment]
A "persist" tag will prevent content from being overwritten. #157 
```
Template:
{% persist "notes" %}

{% endpersist %}
```
Then the content between `%% begin notes %%` and `%% end notes %%` will not be overwritten.

**Comment by jungle-gym-ac** [comment]
Thank you! This solved my problem.
