### ISSUE TITLE
how to delete empty lines

### ISSUE THREAD

**Issue by appwcn** [mgmeyers/obsidian-zotero-integration#283]
`{{annotatedText | replace("\n\n", "\n"))}}`
how to make this code work?

**Comment by FabianUntermoser** [comment]
There seems to one closing bracket too much.

Can you try this?
```
{{annotatedText|replace("\n\n","\n" )}}
```

Note that it might also be the case that it doesnt find a duplicate `\n`, but you can run the replace command twice, in theory.

In the [template from FeralFlora](https://gist.github.com/FeralFlora/78f494c1862ce4457cef28d9d9ba5a01) there are some more advanced replacements, which might be interesting too. Best to go to the raw view of the file thoug.

**Comment by appwcn** [comment]
it works.

sorry, I mistakenly typed two ")"
