### ISSUE TITLE
There was a problem when I used the persist command

### ISSUE THREAD

**Issue by loucdvet123** [mgmeyers/obsidian-zotero-integration#284]
When I build the template using the following command：
```
{% persist "notes" %}
{% endpersist %}
```
It doesn't work, Each time the same document is imported, the content added between `%% begin notes %%` and `%% end notes %%` is repeated.For example, if I repeat the import four times, the contents of `{% persist "notes" %}` and `{% endpersist %}` in the template will be repeated four times in `%% begin notes %%` and `%% end notes %%`.

It does leave the contents of the command intact and not overwritten, but it repeats the contents below the contents. Over and over again

Obsidian version : 1.4.12
zotero integration version : 3.0.10
zotero version : 7.0.0-beta.39+ecba25be0 (64-bit)

**Comment by Lslightly** [comment]
```
{% persist "notes" %}{% if isFirstImport %}
- [ ] first thing
- [ ] second thing
{% endif %}{% endpersist %}
```

add `if isFirstImport` to insert template you want to persist and it won't be repeated in future imports.

**Comment by mgmeyers** [comment]
Yes, as Lslightly says, `isFirstImport` can be used in your template to ensure template text isn't repeated
