### ISSUE TITLE
"Error retrieving item data: duplicates found"

### ISSUE THREAD

**Issue by MarkSant** [mgmeyers/obsidian-zotero-integration#287]
Whenever I try to import a new paper from Zotero, after selected, obsidian informs me this error.
![image](https://github.com/mgmeyers/obsidian-zotero-integration/assets/22659808/b94316ee-8fb6-4713-8c45-20ddaaaf9b65)
And in the console, I get this information:
![image](https://github.com/mgmeyers/obsidian-zotero-integration/assets/22659808/b89dd57e-4912-4fcd-a08c-6dd3b9bbf7b5)
Did anyone came across this error?
Any help?

**Comment by zhangblong** [comment]
I have the same problem. This problem disappears when I clean the trash, and then everything works well. Hope it helpful for guys who meat the same problem.
