### ISSUE TITLE
[Feature Request] Add a Setting to change Zotero port

### ISSUE THREAD

**Issue by vanbang9710** [mgmeyers/obsidian-zotero-integration#288]
Because of a bug in Zotero connector, I need to change the port from 23119 to 23118. But now this plugin can't connect to Zotero

**Comment by mgmeyers** [comment]
@vanbang9710 You can use this setting to specify a custom zotero port:

<img width="699" alt="Screenshot 2023-10-14 at 10 45 52 AM" src="https://github.com/mgmeyers/obsidian-zotero-integration/assets/2694747/288beca8-9fce-4638-8291-7641845a27c1">
