### ISSUE TITLE
Support for Bookends

### ISSUE THREAD

**Issue by redoxmatlab** [mgmeyers/obsidian-zotero-integration#298]
Hi, 
I moved to Bookends https://www.sonnysoftware.com/bookends-for-mac as my universal reference app a few years ago as Zotero is limited in many ways. It would be great if your approach could be adapted to Bookends ? Thoughts?

**Comment by mgmeyers** [comment]
Unfortunately I don't think this would be in scope for this plugin, as it is very specifically designed to work with only Zotero. It would require building an entirely new plugin to support bookends
