### ISSUE TITLE
Importing the Zotero folder path

### ISSUE THREAD

**Issue by haberchr** [mgmeyers/obsidian-zotero-integration#302]
Sorry for messaging here but I don't know of a forum for the plugin:

How do I import the relative path or folder that contains the citation in my directory structure in Zotero? I'd also be interested in accessing the paper and annotation tags in Zotero.

Is there a good starting place to learn about how to find the attributes that are importable that can be passed to a template?

**Comment by mgmeyers** [comment]
@haberchr The best place to look is in the data explorer

<img width="708" alt="Screenshot 2023-10-22 at 9 48 03 AM" src="https://github.com/mgmeyers/obsidian-zotero-integration/assets/2694747/ade3b2f8-67bd-4ca3-8424-cc0401edaa08">

The directory structure is under `collections`
<img width="378" alt="Screenshot 2023-10-22 at 9 49 07 AM" src="https://github.com/mgmeyers/obsidian-zotero-integration/assets/2694747/4bdcfe66-44a8-40ad-85d7-b036d3c0e29b">

Everything else you should also be able to find by looking through the data explorer
