### ISSUE TITLE
[bug] multi-import leads to deletion/override of self-notes

### ISSUE THREAD

**Issue by jprinsen** [mgmeyers/obsidian-zotero-integration#309]
Hi all,

Just a warning. I am extremely pleased with the zotero integration plugin, but experience that self notes inserted in between

> ### Self Notes
> {% persist "notes" %}
> 
> 
> {% endpersist %}
> 

are erased/overwritten when you select and import *multiple* zotero entries in one go. 
This does not happen upon solely selecting one item for import.

**Comment by SimonB97** [comment]
this does also happen for one solely selected item for me. notes added in the actual note, not the template, aren't persisted and notes in the template are stacked.

Obsidian 1.4.16

**Comment by mgmeyers** [comment]
@jprinsen Can you try updating the plugin and see if this issue is fixed?

**Comment by jprinsen** [comment]
> @jprinsen Can you try updating the plugin and see if this issue is fixed?

Mr Meyers, I am extremely grateful for your fix; self notes remain upon importing multiple entries. Thanks a lot!

**Comment by SimonB97** [comment]
I can confirm too, the issue is fixed for me!

Thank you very much for your efforts, great plugin.

**Comment by FeralFlora** [comment]
Looks like this issue can be closed.
