### ISSUE TITLE
Issue with pulling in preview in citations / updating plugin from Zotero database

### ISSUE THREAD

**Issue by dominijk** [mgmeyers/obsidian-zotero-integration#312]
Many thanks for the great plugin. I've noticed a bug (?). As below

- Using citations through command palette i can find a citation and it is added `@citationExample` however for newly added references this doesn't link bank with the live preview as images below 
![Screenshot 2023-11-17 at 11 05 09](https://github.com/mgmeyers/obsidian-zotero-integration/assets/6041913/44b41293-84c5-44bd-8166-adda60fa21f4)
![Screenshot 2023-11-17 at 11 05 03](https://github.com/mgmeyers/obsidian-zotero-integration/assets/6041913/93a0a17f-674f-4b42-a9ef-5979bbb8f3ff)

I'm running on:
- 14.0 (23A344) macOS
- obsidian Version 1.4.16 (Installer 1.4.14)
- with following community plugins
![Screenshot 2023-11-17 at 11 07 48](https://github.com/mgmeyers/obsidian-zotero-integration/assets/6041913/714e76d3-e130-4c28-a005-c122cc26fb48)

What fixes it
- after a period of time and a restart of machine the references appear
- in zotero i've set everything to automatically export as
![Screenshot 2023-11-17 at 11 18 48](https://github.com/mgmeyers/obsidian-zotero-integration/assets/6041913/b0317bdb-b8cd-45c6-a538-b9103c91e59b)

**Comment by FeralFlora** [comment]
@dominijk Wrong plugin, that's Pandoc Reference List.

**Comment by dominijk** [comment]
@FeralFlora which is the tab then?

**Comment by FeralFlora** [comment]
@dominijk Not sure what you mean by tab, but the tooltip you get when hiver is definitely from Pandoc Reference List. Have you set up Pandoc Reference List to work with an exported bibliography, or connecting directly to Zotero?

**Comment by mgmeyers** [comment]
Closing this, as it's an issue with https://github.com/mgmeyers/obsidian-pandoc-reference-list
