### ISSUE TITLE
[BUG] PDF file is still not found after being relocated with Zotero

### ISSUE THREAD

**Issue by nicolnt** [mgmeyers/obsidian-zotero-integration#319]
I took an example of the broken PDF file related to this issue #318.
I downloaded the original PDF for this reference from the Internet, then relocated it using Zotero native dialog box.
Now I can read the PDF from Zotero and all my annotations are still present at the right place they where in the PDF.

However, if I trigger import again from Obsidian Zotero Integration plugin, I still get the error below with the old path to the broken PDF still being the same. The new path after relocation should be the following: `C:\Users\LIENART\Documents\MEGA\References bibliographiques\MartinezEtAl_2020_Optimised production of tailored syngas from municipal solid waste (MSW) by.pdf`

```
Error processing PDF: Command failed with exit code 1: C:\Users\LIENART\Documents\MEGA\Cerveau\.obsidian\plugins\obsidian-zotero-desktop-connector\pdfannots2json.exe /Users/n.lienart/Documents/3_BIBLIO/Énergie/2020_Martínez_Optimised production of tailored syngas from municipal solid waste (MSW) by sorption-enhanced gasification.pdf -w -n base_name -d 120 -f jpg -o C:\Users\LIENART\Documents\MEGA\Cerveau\output_path -q 90
open C:\Users\n.lienart\Documents\3_BIBLIO\Énergie\2020_Martínez_Optimised production of tailored syngas from municipal solid waste (MSW) by sorption-enhanced gasification.pdf: Le chemin d’accès spécifié est introuvable.
```

## EDIT

Zotero logs show that it's looking at the right location. I wonder where the file path used by Obsidian Zotero Integration plugin comes from

```
(3)(+0092165): Viewing attachment 1/J76RNQ3J

(3)(+0000003): Opening C:\Users\LIENART\Documents\MEGA\References bibliographiques\MartinezEtAl_2020_Optimised production of tailored syngas from municipal solid waste (MSW) by.pdf
```

**Comment by willismonroe** [comment]
I'm having the same issue... correct file location is being sent by Zotero (as verified in the Zotero logs) but the import in Obsidian is breaking with the wrong file path.

**Comment by willismonroe** [comment]
So I just went in and added console.logs through the jsonrpc calls and saw that the erroneous file path was actually coming from Zotero (even though it didn't appear in the Zotero logs) so then I suspected that it might be a Better-BibTeX issue (a Zotero plugin). Looking through the Better-BibTex preferences I saw an option to "reset cache" doing that worked perfectly and suddenly it could import just fine into Obsidian.

**Comment by nicolnt** [comment]
> Looking through the Better-BibTex preferences I saw an option to "reset cache" doing that worked perfectly and suddenly it could import just fine into Obsidian.

Oh awesome, thank you for looking into it. I'll definitely try again and re-install this plugin. I close this issue in the meantime
