### ISSUE TITLE
[Bug] Not creating files from itens without PDFs

### ISSUE THREAD

**Issue by henriquebvilela** [mgmeyers/obsidian-zotero-integration#320]
Today I tried to create a new note from an item without a PDF attachment, as I did many times before. The Zotero search bar and the loading screen looked normal, but when it finished no new note was created and no error message was shown. Imports from items with PDF attachments are working fine.

**Comment by kfitz** [comment]
I'm having what I think is the same issue. I successfully created a literature note for a new item with a PDF but cannot create one for an item representing a print book with no PDF.

**Comment by reizen703** [comment]
I'm relieved it's not just me - same issue exactly.

**Comment by mgmeyers** [comment]
Apologies about that, this should be fixed in the latest version. Upgrade and let me know if you still run into issues with this.

**Comment by reizen703** [comment]
Works again - thanks!
