### ISSUE TITLE
some pdf can't import annotations to obsidian (although it has been dispalyed in data explorer)

### ISSUE THREAD

**Issue by wanstarge** [mgmeyers/obsidian-zotero-integration#321]
I can see the annotations item in data explorer
![integration](https://github.com/mgmeyers/obsidian-zotero-integration/assets/70674303/6d40d21a-90ef-499c-89e3-4665103bdcf7)
, and template is here
![template](https://github.com/mgmeyers/obsidian-zotero-integration/assets/70674303/f225e74c-3bda-491c-800b-83312d7f19b6)
but i Can't get the result in obsidian
![result](https://github.com/mgmeyers/obsidian-zotero-integration/assets/70674303/b8f1d5e6-f2a6-41e5-a41c-ebcb15721f3b)

**Comment by lyzcool** [comment]
I have encountered the same problem and hope the developer can answer it

**Comment by RayMacLewis** [comment]
Same here.
A quick fix would be to be able to copy the `Preview Import Format` from the `Zotero Data Explorer` but it does not allow for a copy/paste.

**Comment by mgmeyers** [comment]
Could you update and see if you still encounter this issue in the latest version of the plugin?

Also, please check the developer console for any errors (red text). You can open it with ctrl + shift + i / command + opt + i.

**Comment by RayMacLewis** [comment]
@mgmeyers Man! You are awesome!

Problematic files: Can now be imported again 👍
Console: No errors 👍

Thanks a lot!

**Comment by FeralFlora** [comment]
This issue can be closed.
