### ISSUE TITLE
Annotations show up properly in Zotero Data Explorer but not when used as template variables

### ISSUE THREAD

**Issue by angelineyeow** [mgmeyers/obsidian-zotero-integration#323]
I can see the `annotations` variable having 138 items in Zotero Data Explorer, as shown below. This behaviour is expected.
![image](https://github.com/mgmeyers/obsidian-zotero-integration/assets/45735686/da313e4e-eb55-4e64-9ddf-e6d9f0ffc021)

The following is a segment of my template text
![image](https://github.com/mgmeyers/obsidian-zotero-integration/assets/45735686/0dabc233-241f-4329-a0f0-4c8992df26f1)

When I switch to `Create Literature Note` option, the `annotations` variable exists. This behaviour is expected.
![image](https://github.com/mgmeyers/obsidian-zotero-integration/assets/45735686/14d30d66-bb0e-4daa-83ec-0a413db3e85d)

However, when I run the obsidian command `Zotero Integration: Create Literature Note`, the `annotations.length == 0` condition is true. This behaviour is **unexpected**.
![image](https://github.com/mgmeyers/obsidian-zotero-integration/assets/45735686/cf442ffd-d070-43bb-9b5a-f048b2db27bc)

The following is the output of the command. This behaviour is **unexpected**.
![image](https://github.com/mgmeyers/obsidian-zotero-integration/assets/45735686/8b0c8b30-90a6-4593-bfc1-cb676f0137ff)

As you can see, using Zotero Data Explorer, with the `Create Literature Note` option, we don't see the text `test2`. However, if we run the obsidian command `Create Literature Note`, we see the text `test2`.

**Comment by mgmeyers** [comment]
@angelineyeow could you update and see if you still encounter this issue in the latest version of the plugin?

Also, please check the developer console for any errors (red text). You can open it with ctrl + shift + i / command + opt + i.

**Comment by mgmeyers** [comment]
Closing this. Let's keep track in #321
