### ISSUE TITLE
New Better BibteX Version breaks Zotero Obsidian Import

### ISSUE THREAD

**Issue by cstelmach** [mgmeyers/obsidian-zotero-integration#329]
Hi. 

### Problem:
The new Better BibTeX for Zotero addon updates `v6.7.141`, `v6.7.142` and `v6.7.143` are currently breaking the Import into Obsidian, giving the error notification `Unexpected end of JSON input`.

I my case the Zotero addons update automatically. So some might encounter the same error. 

### Recreation: 
A quick check is to try to use Data Explorer to open any publication, leading to an error notification `Unexpected end of JSON input` and following console error messages:

```
plugin:obsidian-zotero-desktop-connector:98 SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at nr (plugin:obsidian-zotero-desktop-connector:98:8531)
    at async Yx (plugin:obsidian-zotero-desktop-connector:112:4851)
nr @ plugin:obsidian-zotero-desktop-connector:98
```
```
plugin:obsidian-zotero-desktop-connector:112 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'length')
    at Yx (plugin:obsidian-zotero-desktop-connector:112:4934)
 ```

### Workaround:
What currently works for me is to remove the Zotero Addon `Better BibTeX for Zotero` and download a compatible version [v6.7.140](https://github.com/retorquere/zotero-better-bibtex/releases/tag/v6.7.140). Then turn off the automatic update for this addon (until the problem is fixed).

### Todo:
Please fix this issue for the new versions or modify the error message with the current solution.
Thanks.

**Comment by jinze1234599** [comment]
I am facing the same problem, hoping for the solution

**Comment by ecology-rocks** [comment]
I also have the same issue!

**Comment by mgmeyers** [comment]
Hey all, I've released a new version with a fix for this. Update and let me know if you have any futher issues.

**Comment by ecology-rocks** [comment]
It works for me! (Idk if this comment will reopen the issue. If it does, so sorry!)

**Comment by ajpelu** [comment]
It works!!. Thanks for update

**Comment by harrisluket** [comment]
Hi unfortunately I am still getting the same error message even after updating. To make sure I uninstalled BBT from Zotero and reinstalled with the latest version, but I still get the same message when trying to import from Zotero in obsidian. Thank you!

**Comment by SarahJMills** [comment]
Worked for me too, very many thanks.

**Comment by harrisluket** [comment]
> Hi unfortunately I am still getting the same error message even after updating. To make sure I uninstalled BBT from Zotero and reinstalled with the latest version, but I still get the same message when trying to import from Zotero in obsidian. Thank you!

I resolved this. For anyone still having issues make sure that you also update the Zotero Integration plugin in Obsidian to the latest version. Everything works well now.

**Comment by devinat1** [comment]
Worked thanks!

**Comment by GillesSanMartin** [comment]
Looks like this problem is back with the last versions of better bibtex and Obsidian Zotero integration plugin...

**Comment by mohsinmalikali** [comment]
> Looks like this problem is back with the last versions of better bibtex and Obsidian Zotero integration plugin...
> 
> Edit : sorry, maybe not the same problem :
> 
> message from Zotero : Better BibTex: CAYW Failed. id is undefined
> 
> Message from Obsidian : Error Retrieving Cite Key : Request Failed. Status 500

I'm having the same problem after the new update

**Comment by KonstantinLackner** [comment]
Just wanted to add that I have the same issue.
I get the "error retrieving cite key" message as well. Generally speaking, the fields that the data explorer in zotero for obsidian shows are not available.
