### ISSUE TITLE
error retrieving item data: unexpected end of JSON input

### ISSUE THREAD

**Issue by zzhixin** [mgmeyers/obsidian-zotero-integration#330]
Have installed better bibtex for zotero. 
Import note is fine. 
When I use data explorer, after search paper, the following error occurs:

![image](https://github.com/mgmeyers/obsidian-zotero-integration/assets/40470855/9e1c8f49-7041-43cf-a302-fad3fce0d340)

**Comment by t-ober** [comment]
There is a workaround mentioned by reinstalling and fixing the BetterBibTex addon mentioned [here](https://github.com/mgmeyers/obsidian-zotero-integration/issues/329)

**Comment by mgmeyers** [comment]
Hey all, I've released a new version with a fix for this. Update and let me know if you have any futher issues.
