### ISSUE TITLE
import note from zotero to  obsidian failed. 

### ISSUE THREAD

**Issue by jackspp** [mgmeyers/obsidian-zotero-integration#38]
<img width="304" alt="截屏2022-04-18 下午11 04 14" src="https://user-images.githubusercontent.com/26614488/163829803-d380ee77-0903-41f7-9995-8b22d528e1da.png">

it failed like this. seems like pdf utility problem. 

6.0.5-beta.5 + obsidian 0.14.5 + obsidian-zotero-desktop-connector 1.2.26 + macbook m1

**Comment by ohneb** [comment]
Hey, I have the exact same error. Some segementation fault when trying to OCR a pdf from zotero.
I'm currently using:
- Zotero 6.0.4
- Obsidian 0.14.6
- Obsidian Zotero Desktop Connector 1.2.26
- on Fedora Workstation Linux 36
If I can be of any help debugging this issue just let me know. I will try to do some debugging on my own in the meantime although I am not very familiar with Go and the PDF libraries you're using.

Let me know if it is better to open an issue in the pdf2json repo.

Thanks for your work and support! It's really appreciated and I am looking forward to really get into using your plugin.

Cheers,
Ben
