### ISSUE TITLE
Zotero wont import for created improt format 

### ISSUE THREAD

**Issue by SwamiVT** [mgmeyers/obsidian-zotero-integration#386]
After updating to zotero 7, my old import template shows this specific error

Obsidian: 1.6.7
Plugin: 3.2.1
betterBibTeX: 6.7.222
Zotero: 7.0.1

Error shown by on the screen
![image](https://github.com/user-attachments/assets/8a28a13b-28ac-42de-acc1-b5e0f340e5ee)
Import format
![image](https://github.com/user-attachments/assets/4b85dff8-a0e0-43e2-a2e9-44d10669f199)
Template for the import
![image](https://github.com/user-attachments/assets/50b7c6ce-0e37-423b-acc2-5b22aed47254)

**Comment by mgmeyers** [comment]
Does anything change if you uninstall and reinstall better bibtex? A few users have reported having to do this after updating to zotero 7

**Comment by SwamiVT** [comment]
The error turns out to be related to a syntactic error on my part in the template, due to a missing double quote.
