### ISSUE TITLE
Zotero picker bar

### ISSUE THREAD

**Issue by menagerie198** [mgmeyers/obsidian-zotero-integration#4]
The Zotero citation picker bar thingy stays in the background. Is there a way of forcing it to the surface - always on top, kind thing?

**Comment by eleanorkonik** [comment]
I was coming here to request the same thing 😅

**Comment by ReaderGuy42** [comment]
Same :) Thanks!

**Comment by mgmeyers** [comment]
@menagerie198 @eleanorkonik & @ReaderGuy42 What OS are all of you using?

**Comment by ReaderGuy42** [comment]
I'm on Linux Mint 20.3

**Comment by eleanorkonik** [comment]
I'm on Windows

**Comment by menagerie198** [comment]
Windows 10. After a first usage, where I have to look behind the Obs window, the picker rises to the surface on subsequent uses.

**Comment by laurastephsmith** [comment]
I've not had a problem with the ZDC picker that I've noticed, but after reading this I think I've had the same problem with opening *any* window when Obsidian is in the foreground. I hadn't connected it with Obsidian until now, thought it was a system-wide thing. But if I press my super+w key for Firefox (or other app launcher shortcuts) it opens behind Obsidian. But like you have with the picker, @menagerie198, after one go it comes to the front after that, at least for a while. Have any of you noticed if this happens with you? I'm on Debian with Gnome 40-something.

**Comment by mgmeyers** [comment]
So, I'm not sure there's much I can do about this issue, unfortunately. The picker bar is created by Zotero and not this plugin, and I don't see any way to ensure it remains on top. I'll keep an eye out for a fix, but I'm going to close this for now.

**Comment by mehrangta** [comment]
Go to your Zotero program, Click 'edit', 'preferences', 'advanced' and then click 'config editor' down near the bottom. Click 'I accept the risk'. This will bring up the config editor.

In the search bar at top, search for 'integration', and find the line item:

extensions.zotero.integration.keepAddCitationDialogRaised

If its value is 'false', you need to change it to 'true'.
Right-click on it, and select 'toggle', to toggle it to 'true'.
Then close the window.
This fixed the problem for me.

**Comment by ReaderGuy42** [comment]
@mehrangta This actually causes a problem for me, see https://github.com/mgmeyers/obsidian-zotero-integration/issues/249

reversing this change solves the problem noted in that issue.
