### ISSUE TITLE
an imported note from zotero "select area" misses link back to pdf

### ISSUE THREAD

**Issue by erazlogo** [mgmeyers/obsidian-zotero-integration#41]
I use Zotero annotation function and then use ZDC to import via "make note from annotations" in Zotero. Zotero's own markdown export from "select area" annotations doesn't export images, but it does include a link back to the pdf selected area. But when I import via ZDC, the link is missing. Any chance this could be fixed? Thanks!

**Comment by mgmeyers** [comment]
This has been fixed!
