### ISSUE TITLE
Sanitize {{title}} if used in filename - case of slash `/`

### ISSUE THREAD

**Issue by danieltomasz** [mgmeyers/obsidian-zotero-integration#42]
Great plugin! :)

For template` {citekey}} - {{title}}.md`  and  paper named

 `Large-Scale Topographical Analysis of Electrophysiological 1/f and Oscillations Reveals Patterns of Spatial Variation`  the `/` is interpreted as  folder path and the result is 
 the file `f and Oscillations Reveals Patterns of Spatial Variation` in  a folder `donoghue2019 Large-Scale Topographical Analysis of Electrophysiological 1` 

Unfortunately, reference to 1/f distribution is quite often in titles in my library ;)

**Comment by mgmeyers** [comment]
This is trickier than it seems on my end, but I'll see if there's a good way to go about it. In the mean time, you can do something like:

```
{{citekey}} - {{title | relace("/", "_")}}.md
```

**Comment by danieltomasz** [comment]
Thanks, it is really useful, I returned to this problem again :)  One remark for people who will see it later it should be 

```
{{citekey}} - {{title | relace("/", "_")}}.md
```
There was typo above :)
