### ISSUE TITLE
pdf extract fail， go runtime issue？

### ISSUE THREAD

**Issue by hpxing** [mgmeyers/obsidian-zotero-integration#45]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x446c23b]

goroutine 91 [running]:
main.getTextByAnnotBounds(0x0?, 0x0?, 0x4060d5c28f5c28f6?, {{0x4072f0a3d70a3d71?, 0xc007b46000?}, {0xe88?, 0x43d83df?}})
	github.com/mgmeyers/pdf-annots2json/helpers.go:95 +0x3b
main.processAnnotations.func1()
	github.com/mgmeyers/pdf-annots2json/main.go:279 +0xa1a
golang.org/x/sync/errgroup.(*Group).Go.func1()
	golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:57 +0x67
created by golang.org/x/sync/errgroup.(*Group).Go
	golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:54 +0x8d

**Comment by hpxing** [comment]
![uTools_1651301145408](https://user-images.githubusercontent.com/43682925/166095114-62a13753-a164-4741-b201-a0d92ccceaeb.png)

**Comment by mgmeyers** [comment]
@hpxing Do you still get this error with the latest update?

**Comment by hpxing** [comment]
this issue is fixed.Thanks ~  But have a another issue!
