### ISSUE TITLE
after the update, the date explorer can have data ,but import note is nothing.

### ISSUE THREAD

**Issue by hpxing** [mgmeyers/obsidian-zotero-integration#47]
the 2.1.8 version
---

# TP

### Formatted Bibliography

{{bibliography}}
{% if abstractNote %}

### Abstract

{{abstractNote}}
{% endif %}

{% for annotation in annotations %}
{% if annotation.annotatedText %}

> {{annotation.annotatedText}}
> {% endif %}
> {% if annotation.comment %}
> {{annotation.comment}}
{% endif %}
{% endfor %}

---

### Formatted Bibliography

(1)

Villamil Jiménez, J. A.; Le Moigne, N.; Bénézet, J.-C.; Sauceau, M.; Sescousse, R.; Fages, J. Foaming of PLA Composites by Supercritical Fluid-Assisted Processes: A Review. _Molecules_ **2020**, _25_ (15), 3408. [https://doi.org/10.3390/molecules25153408](https://doi.org/10.3390/molecules25153408).

### Abstract

Polylactic acid (PLA) is a well-known and commercially available biopolymer that can be produced from different sources. Its different characteristics generated a great deal of interest in various industrial fields. Besides, its use as a polymer matrix for foam production has increased in recent years. With the rise of technologies that seek to reduce the negative environmental impact of processes, chemical foaming agents are being substituted by physical agents, primarily supercritical fluids (SCFs). Currently, the mass production of low-density PLA foams with a uniform cell morphology using SCFs as blowing agents is a challenge. This is mainly due to the low melt strength of PLA and its slow crystallization kinetics. Among the different options to improve the PLA characteristics, compounding it with different types of fillers has great potential. This strategy does not only have foaming advantages, but can also improve the performances of the final composites, regardless of the implemented foaming process, i.e., batch, injection molding, and extrusion. In addition, the operating conditions and the characteristics of the fillers, such as their size, shape factor, and surface chemistry, play an important role in the final foam morphology. This article proposes a critical review on the different SCF-assisted processes and effects of operating conditions and fillers on foaming of PLA composites.  

【摘要翻译】聚乳酸（PLA）是一种广为人知的商用生物聚合物，可从不同来源生产。其不同的特性在各个工业领域引起了极大的兴趣。此外，近年来，其作为泡沫生产的聚合物基质的用途有所增加。随着寻求减少工艺对环境的负面影响的技术的兴起，化学发泡剂正被物理剂取代，主要是超临界流体（SCF）。目前，使用单细胞纤维作为发泡剂大规模生产具有均匀泡孔形态的低密度PLA泡沫是一个挑战。这主要是由于PLA的低熔体强度和缓慢的结晶动力学。在改善聚乳酸特性的各种选择中，将其与不同类型的填料复合具有很大的潜力。该策略不仅具有发泡优势，而且可以改善最终复合材料的性能，无论采用何种发泡工艺，即分批、注射成型和挤出。此外，填料的操作条件和特性，如尺寸、形状因子和表面化学，对最终泡沫形态起着重要作用。本文对不同的SCF辅助工艺以及操作条件和填料对PLA复合材料发泡的影响进行了综述。

> LA Composites by f PLA Compos sted Processes:
> 
> 
> ǍN4uLmAOSRz[PLAYTgPevllċ

> mposite; nanocomposite; super
> 
> 
> 聚乳酸；生物复合材料；纳米复合材料；超临界流体；泡沫

> 

%% Import Date: 2022-04-30T20:26:20.685Z %%

**Comment by mgmeyers** [comment]
Hmm, so data explorer creates the note correctly, but not when you run the import? Could you share how your `Output Path` is set in settings?

Also, are there any errors in the developer tools?

<img width="237" alt="Screen Shot 2022-04-30 at 2 03 05 PM" src="https://user-images.githubusercontent.com/2694747/166122585-852d136e-5bd3-4388-8e84-11efcebee02a.png">

<img width="773" alt="Screen Shot 2022-04-30 at 2 04 08 PM" src="https://user-images.githubusercontent.com/2694747/166122623-bdd89694-f19f-4372-b00f-0b7387f9a6ea.png">

**Comment by hpxing** [comment]
![uTools_1651369562946](https://user-images.githubusercontent.com/43682925/166128675-c014af27-8d41-494b-ab14-ab64572c7ea9.png)

**Comment by hpxing** [comment]
There is no error. And the file is created in the folder I set, but nothing in it

**Comment by danieltomasz** [comment]
1) For importing notes the output  is empty too (empty file with  a cite key as name), 
2)  had saved import format with template,  and there is no file created since the update to 2.0.8, in both cases, there is no error in the console

**Comment by mgmeyers** [comment]
@hpxing There should be two commands. One is "Import notes" which imports notes like these from Zotero:

<img width="276" alt="Screen Shot 2022-05-01 at 10 28 43 AM" src="https://user-images.githubusercontent.com/2694747/166157219-e65b1c6d-be02-41cd-8550-08408902a63f.png">

Then another command with the same name as your import format.

<img width="644" alt="Screen Shot 2022-05-01 at 10 29 39 AM" src="https://user-images.githubusercontent.com/2694747/166157301-8fb48013-6706-429a-9b07-8b378db13451.png">

<img width="717" alt="Screen Shot 2022-05-01 at 10 30 07 AM" src="https://user-images.githubusercontent.com/2694747/166157307-9535d8f9-a534-46d9-9c9f-452aa2c2f6ff.png">

Just to clarify, which import isn't working for you?

**Comment by hpxing** [comment]
sorry It works。
 I use wrong import， cause my tp name is import ，I used the import notes 。 I should use import 1#，as this is my tp name。
By the way ，the annotion form pdf extract have no link to the page which annotion is in。 And it is not backlinked to zotero。

**Comment by hpxing** [comment]
In zotero
<img width="488" alt="uTools_1651457247270" src="https://user-images.githubusercontent.com/43682925/166176152-23455d9d-75c1-44fe-b600-e9d0ded981af.png">
---
import notes into ob

![1651457275065](https://user-images.githubusercontent.com/43682925/166176196-c5b53430-672c-4f96-90d4-3db8e74fa32d.png)
NO pictures，only the link。

**Comment by sjgknight** [comment]
I know this was now a long time ago, but just in case someone else comes by (or, @hpxing still useful to you), Zotero stores the note-images as annotations even when they're in a built note...it's annoying. The template below may help but it isn't fully functional (it will output the image links, but also multiple modified copies of list...). It filters annotations to just images, checks if their ids exist in the note, and replaces those with themselves+the image relative path.

```
{%- set annotationImage = annotations | filterby("type", "contains", "image") -%}

{% if annotationImage %}
	{% for annotation in annotationImage %}
	{% set idx = [annotation['id'], ")"] | join %}
	{% set idxreplace = [idx, " ![[{{", annotation['imageRelativePath'], "}}]]"] | join %}
		{% if annotation['id'] in note.note %}
			{{ note.note | replace(idx, idxreplace) }}
		{% endif %}
	{% endfor %}
{% endif %}

{{note.note}}

```
