### ISSUE TITLE
Add {{collections}} to fetch the collection(s) of the item in Zotero

### ISSUE THREAD

**Issue by xjtusjtu** [mgmeyers/obsidian-zotero-integration#48]
Hi, bro!

This is a very nice plugin, and I very like it! However, I find that there is no field data to fetch the information about the collection(s) of the item in Zotero

If possible, it could not be better that there would be a such placeholder!

I will appreciate it if you could cnsider this possible enhancement!

![image](https://user-images.githubusercontent.com/57665402/166177832-b2d9b5bb-7108-4328-aeff-b2ba0b9930ec.png)

**Comment by xjtusjtu** [comment]
In Mdnotes for Zotero (a Zotero plugin) can fetch such data through "{{collections}}"
In Citations (an Obsidiian plugin) can fetch such information, if we set "Include JabRef-specific metadata:" in Better Bibtex 😁

**Comment by mgmeyers** [comment]
This currently isn't possible, but will be once this PR for the better bibtex plugin is updated and merged: https://github.com/retorquere/zotero-better-bibtex/pull/2141

**Comment by xjtusjtu** [comment]
OK, I got it! Thank you very much, bro!

**Comment by xjtusjtu** [comment]
I want to add that: if I make such configuration 👇 in Better Bibtex
![image](https://user-images.githubusercontent.com/57665402/168589295-88e28af3-8ef7-449f-9a77-a094c986bdb9.png)

the exported .bib file contains 👇
![image](https://user-images.githubusercontent.com/57665402/168589958-42f0c415-3bef-4dc8-8846-3e5d6e134b0e.png)

![image](https://user-images.githubusercontent.com/57665402/168590286-ca0aa42c-7f42-4b70-a4aa-72bd937cc19f.png)
