### ISSUE TITLE
[feature request] insert item metadata into current note

### ISSUE THREAD

**Issue by erazlogo** [mgmeyers/obsidian-zotero-integration#51]
The plugin can insert Zotero item notes into current Obsidian note, but sometimes it is useful to just add the metadata. 

Use case: I often need to add a link to a Zotero item to a note. I need more than just a Bibtex citekey so I recognize what it is. I would love to be able to create a template with a bibliographic reference + URI  (link to the item in Zotero) and then just add that into the note. I know that I can already add a footnote/bibliographic reference, but a link to a Zotero item is also necessary.

Any chance you could add this option? Thanks!

**Comment by mgmeyers** [comment]
This should now be possible @erazlogo. I've added a new "template" citation format. Let me know if you run into any issues with it!

<img width="725" alt="Screen Shot 2022-07-26 at 11 49 13 AM" src="https://user-images.githubusercontent.com/2694747/181087684-2b0c77bf-d6ce-4376-a737-9cc5d74645af.png">
