### ISSUE TITLE
Using PDFs moved outside of Zotero

### ISSUE THREAD

**Issue by andrewcrook** [mgmeyers/obsidian-zotero-integration#52]
If I use [Zotfile](http://zotfile.com/) to move or other method to move my PDFs outside of Zotero into a folder indexed for example by [DevonThink 3](https://www.devontechnologies.com/apps/devonthink)(my main PDF manager)
Would it possible to for the Obsidian Zotero Integration Plugin  to follow the link to the path stored in Zetero of the said PDF to extract annotations. 

<img width="649" alt="image" src="https://user-images.githubusercontent.com/803618/170370037-6027f801-23de-43a6-9f98-41d51728bcc4.png">

The main reason I wish to use this plugin is so I can extract annotated images. The Zotero plugin MDnotes allows me to copy annotations to notes then export to markdown, however, doesn’t follow through with annotated images.

**Comment by mgmeyers** [comment]
@andrewcrook Yes, this should already be possible. I use zotfile to move my PDFs into my iCloud storage, and am able to extract annotations from them.

**Comment by andrewcrook** [comment]
> @andrewcrook Yes, this should already be possible. I use zotfile to move my PDFs into my iCloud storage, and am able to extract annotations from them.

@mgmeyers Thanks got it working
