### ISSUE TITLE
Note creation fails with some zotero items

### ISSUE THREAD

**Issue by sirpbele** [mgmeyers/obsidian-zotero-integration#58]
Hey,

I am very new to obsidian and my knowledge about programming is quite neglectable.
I want to use Obsidian with this plugin to create notes from information about my zotero items (research papers, in my case) with the annotations I made in Zotero (inbuilt reader of Zotero 6).

I'm using obsidian v0.14.6 and Zotero 6.0.8

I managed to create notes from  some papers using erazlogo's template without tags (https://forum.obsidian.md/t/zotero-desktop-connector-import-templates/36310/2). Displaying my annotations only works after I created a note from my annotations, but I guess this is because I am using the inbuilt Zotero PDF reader for annotating?

However, with some papers the creation of a new note doesn't work. The error message I get in obsidian is:
"Error processing pdf: command failed with exit code 1: *path to .obsidian/plugins/obsidian-zotero-desktop-connector\pdfannots2json.exe* *path to zotero item\full-text.pdf* -n image -d 120 -f jpg -o *path to Image output path\citekey* -q 90 fitz: cannot open document"

I guessed that it has something to do with the image output path. So I tried creating the folder "Images" when the image output path was set to "Images/{{citekey}}/". I also tried deleting the image output path, but the only thing changing is the image output path in the error message :)

I'm sorry if this is the wrong place to post this or if the information I'm providing is not sufficient. Just let me know.

**Comment by mgmeyers** [comment]
Hi @sirpbele,

Re: the first issue, currently this plugin doesn't have access to annotations created with Zotero's native PDF reader, but it can important if you create a note like you mentioned.

Re: the second, that error means that the plugin can't open your PDF file for some reason. Do other PDFs give you this error as well?

**Comment by sirpbele** [comment]
Hi @mgmeyers,

thanks for the reply. I tried again now and it works with some references/PDFs and with others, it doesn't. I noticed that in my zotero, some PDFs attached to a reference are simply named "PDF" whilst others are named "Author et al - Year - Beginning of title", but this doesn't seem to correlate with wether I can create a note from it or not. Also, I moved my Mendeley library to Zotero, but again some of the references that can be imported to obsidian were added afterwards and some were transferred from Mendeley to Zotero. For now I can't give you more useful information - I guess this is not enough to find a reason.

**Comment by sirpbele** [comment]
I actually used Adobe Acrobat now to save the PDF again and it solved the issue with 2 of 2 references that I tried so far. I didn't try that before because saving it as an Adobe PDF file was the only option under "save as", so I thought this wouldn't change anything - but it did :)
So in Zotero I right clicked -> show file -> open PDF in Acrobat reader -> File - Save as -> overwrite previous file as "Adobe PDF file"
And afterwards it worked perfectly. Thanks for the suggestion @jdmorg0
