### ISSUE TITLE
renaming commands creates multiple commands 

### ISSUE THREAD

**Issue by MichaBrugger** [mgmeyers/obsidian-zotero-integration#61]
Amazing plugin, but something small I noticed: It seems that when renaming the import or cite variants it creates a command for every letter you type (see picture below). Nothing too tragic, but probably not intended. Cheers!

![image](https://user-images.githubusercontent.com/46029522/173193982-57fa89f3-e12a-4a18-a37f-68bf4ed65008.png)

**Comment by unamunoe** [comment]
I've faced the same issue, but it seems that restarting Obsidian removes the "partial entries" you mention.
