### ISSUE TITLE
Add mechanism to limit search to a specific Zotero collection

### ISSUE THREAD

**Issue by Gnossos** [mgmeyers/obsidian-zotero-integration#64]
[[Proposed Label: Enhancement Request]]

This is an enhancement request for those of us with large numbers of references in Zotero. For citations, bibliography entries, imported sources, and imported associated annotations from attached pdf's, I'd like a way to limit searches using Zotero's Desktop Connector to one or more specific collection(s). E.g., {Collection 1, Collection 2, Collection 3} or {"statistical software", "programming", "R packages"}.

**Comment by mgmeyers** [comment]
@Gnossos you can do this by switching to the classic view of the zotero picker:

<img width="815" alt="Screen Shot 2022-06-29 at 12 41 41 PM" src="https://user-images.githubusercontent.com/2694747/176524658-80f8a07b-29c8-43ad-a365-5dcec98a326c.png">

<img width="949" alt="Screen Shot 2022-06-29 at 12 42 40 PM" src="https://user-images.githubusercontent.com/2694747/176525096-1f6fe1c6-7e75-4fed-bc7c-7f57289880e6.png">

This plugin doesn't have any control over the picker, however, as it is built into Zotero.
