### ISSUE TITLE
"Import Note" function failed to overwrite

### ISSUE THREAD

**Issue by Raagaception** [mgmeyers/obsidian-zotero-integration#69]
I'm having some issues updating created notes with the latest annotations from Zotero. After reading [this section of the documentation](https://github.com/mgmeyers/obsidian-zotero-integration/blob/main/docs/Templating.md#how-do-i-prevent-sections-of-my-templates-from-being-overwritten), I wasn't able to get the plugin to overwrite my notes at all. The steps I followed:
1. Made 2 annotations within Zotero 6 (inside the Zotero PDF reader instead of opening in default app; not sure whether it's relevant or not!)<br>![image](https://user-images.githubusercontent.com/72780589/178400529-1e001441-65bb-4c92-8c66-2ae9280c1110.png)
2. Used the "Add note from annotations" function (instead of using ZotFile like in Zotero 5, it's native in Zotero 6. AGAIN not sure whether this is relevant)
3. Used the ``Import Note`` function (as opposed to using a template, I assume the overwriting issue would be the same either way?) which create the following note<br>
![image](https://user-images.githubusercontent.com/72780589/178401324-03a0060a-3225-4ce6-8946-8c3329eccf4a.png)
4. Added more random annotations, and repeated step 2 *without* deleting the old annotations file. (now there are two extracted annotations, with two different extract dates)<br>
![image](https://user-images.githubusercontent.com/72780589/178402281-9bb47daf-6a56-41c5-8588-2a41cef6232f.png)
5. Ran the ``Import Note`` function again, but this error pops up and the note doesn't get updated<br>
![image](https://user-images.githubusercontent.com/72780589/178402441-886ca99f-8bcb-432a-ad9f-950345fb9415.png)

Have tried this entire process with creating a note through an import format, then using the import function but to no avail. Am I doing something wrong my end?

**Comment by mgmeyers** [comment]
This should be fixed in the latest version. Try updating. If you run into issues feel free to open another ticket.
