### ISSUE TITLE
FR get correct page number for the annotation in Zotero 6

### ISSUE THREAD

**Issue by erazlogo** [mgmeyers/obsidian-zotero-integration#70]
In Zotero 6 annotations, there is a way for a user to override the PDF page number and insert the correct page number for the quote (i.e. if the article has 20 pages in the PDF but it's actual page numbers are 101-120). Would it be possible to get that corrected page number into the Data Explorer? Thanks!

**Comment by kfitz** [comment]
I see that this request has been closed as completed, but I'm having issues with this: I have a PDF whose page range is 365-386, and those page numbers appear properly in both Zotero 6 and on the PDF when opened in Preview, but annotation.page is still using 1-21...
