### ISSUE TITLE
Support for custom citation styles?

### ISSUE THREAD

**Issue by MsArivia** [mgmeyers/obsidian-zotero-integration#72]
It would be nice if the Formatted Citation and Formatted Bibliography options allowed for you to use your own citation styles. I've written one and have it in my Zotero install, but this plugin seems to pull from the list on the official Style Repository, and I'd rather not upload there yet while I'm dogfooding my own version.

(In case you're wondering why I wrote my own citation style: it's for sorting out 50+ years of Dungeons and Dragons books, where "edition" means something significantly different from most other formats.)

**Comment by MsArivia** [comment]
I talked to mgmeyers on the obsidian discord and he added support!
As of 2.2.10, you can manually enter a custom CSL style's ID in the drop down list where you would select a standard CSL format, and it works!

The ID for your custom style looks something like this inside the file: <id>http://www.zotero.org/styles/rpg-style</id>. In this case, I enter rpg-style in the list control and it works.

Thanks for the help mgmeyers!

**Comment by jmdelahanty** [comment]
Hello @MsArivia ! I'm curious if you know whether or not this still works. I'm trying to do a small custom thing just to learn how some of these tools work and I can't seem to get it right. I have the .csl installed to Zotero and Zotero recognizes it, but when I search for it in the drop down in my obsidian vault it doesn't show up quite yet. Any tips?

**Comment by nicolnt** [comment]
> Hello [@MsArivia](https://github.com/MsArivia) ! I'm curious if you know whether or not this still works. I'm trying to do a small custom thing just to learn how some of these tools work and I can't seem to get it right. I have the .csl installed to Zotero and Zotero recognizes it, but when I search for it in the drop down in my obsidian vault it doesn't show up quite yet. Any tips?

Yes it still works. Just paste the id and press enter. There is nothing else to select from the dropdown.

With MsArivia example style:

<img width="1159" height="226" alt="Image" src="https://github.com/user-attachments/assets/e81cd487-4b80-4644-b191-0abedd75f01f" />
