### ISSUE TITLE
"Import notes" / "Insert notes into current document" not working

### ISSUE THREAD

**Issue by nmariano9** [mgmeyers/obsidian-zotero-integration#74]
Maybe I am doing something incorrectly, but "Import notes" and "Insert notes into current document" is now failing to import highlighted annotations made using the Zotero PDF viewer. "Import notes" creates a blank note, "Insert notes" does nothing to the note. 

However, my custom import using a template is still working as it should. 

I am using Zotero 6.0.11 and Obsidian 0.15.6 on MacOS. 

Thanks!

**Comment by nmariano9** [comment]
Started working again.... Maybe a Zotero thing.

**Comment by frederike-petzschner** [comment]
Not working for me either. It worked once and now creates the note but with zero content. Anyone encountered the same issue?
