### ISSUE TITLE
Markdown is not updated when the same entry is imported multiple times

### ISSUE THREAD

**Issue by Miscellan** [mgmeyers/obsidian-zotero-integration#77]
Obsidian: 0.15.9
Zotero integration: 2.2.18

I set up my template according to the instructions in the template.md documentation.
This is my template:
```
{% persist "annotations" %}

## Annotation

{% for annotation in annotations %}
{% if annotation.color == '#ffd400' %}
{{annotation.comment}}
<font color=#ca6924>{{annotation.annotatedText}}</font>
{{pdfZoteroLink|replace("//select/", "//open-pdf/")|replace(")", "")}}?page={{annotation.page}}&annotation={{annotation.id}})
{% endif %}

{% if annotation.color == '#ff6666' %}
{{annotation.comment}}
<font color=#c3272b>{{annotation.annotatedText}}</font>
{{pdfZoteroLink|replace("//select/", "//open-pdf/")|replace(")", "")}}?page={{annotation.page}}&annotation={{annotation.id}})
{% endif %}

{% if annotation.color == '#a28ae5' %}## {{annotation.annotatedText}}{{annotation.comment}}
{% endif %}

{% if annotation.color == '#2ea8e5' %}### {{annotation.annotatedText}}{{annotation.comment}}
{% endif %}

{% if annotation.color == '#5fb236' %}
{{annotation.comment}}
<font color=549688>{{annotation.annotatedText}}</font>
{{pdfZoteroLink|replace("//select/", "//open-pdf/")|replace(")", "")}}?page={{annotation.page}}&annotation={{annotation.id}})
{% endif %}

{% if annotation.imageBaseName %}
![[{{annotation.imageBaseName}}]]
{% endif %}
{% endfor %}

{% endpersist %}
```
However, when I tried to import notes from the same paper again, the corresponding notes in Obsidian were not updated.
First Import: 
![first.jpg](https://img1.imgtp.com/2022/07/29/cjGtlEAC.jpg)

data explorer:
![data explorer.jpg](https://img1.imgtp.com/2022/07/29/hVejIipZ.jpg)

import again:
![import again.jpg](https://img1.imgtp.com/2022/07/29/NaWk7sx2.jpg)

The notes didn't change at all. What do I need to do to update my markdown notes successfully?

**Comment by mgmeyers** [comment]
@Miscellan What OS are you on? Also, how many annotations do you see in the data explorer?

<img width="221" alt="Screen Shot 2022-07-28 at 10 20 38 PM" src="https://user-images.githubusercontent.com/2694747/181688093-6b4cc93b-96b2-49fc-83e2-bac70fcdead3.png">

**Comment by Miscellan** [comment]
I am on Windows 10. Because the notes mentioned above were for tests, I didn't save them. So I test again. There are the results. The problem remains. 

The first Data explorer:
![first.jpg](https://img1.imgtp.com/2022/07/30/Fzecs15D.jpg)

Import time:
![first import.jpg](https://img1.imgtp.com/2022/07/30/vIMch2nX.jpg)

The second Data explorer:
![second.jpg](https://img1.imgtp.com/2022/07/30/alCg6HUh.jpg)

**Comment by mgmeyers** [comment]
@Miscellan I think I was able to fix this. Can you update the plugin and try again?

**Comment by Miscellan** [comment]
@mgmeyers 
I updated the plug-in to v2.2.23 and tested it again.
But unfortunately, the problem don't resolve. The preview in data explorer has updated. But the markdown notes have no change.

The first time and results:
![first and first result.jpg](https://img1.imgtp.com/2022/08/12/xF6PBthk.jpg)

The second time and results:
![second and second result.jpg](https://img1.imgtp.com/2022/08/12/1bBvU9Sl.jpg)

**Comment by yyqww** [comment]
I have the same problem. Have you solved it？
i have describe this problem in there.
#119

**Comment by mgmeyers** [comment]
Try updating to the latest version and see if you still encounter problems with this. If so, please open another issue.
