### ISSUE TITLE
Updating the names of import and citation formats will create multiple instances in the command palette

### ISSUE THREAD

**Issue by NeoNewton01** [mgmeyers/obsidian-zotero-integration#78]
Every time the names of citation and import formats are updated, it creates a new command in the command palette, but it does not delete previous commands. The commands that should have been deleted do not work.

For example, if you type "Harvard Bibliography" as a Citation Format, the command palette will show:
.......
- ZOTERO INTEGRATION. Harvard Bi
- ZOTERO INTEGRATION. Harvard Bibl
- ZOTERO INTEGRATION. Harvard Biblio
- ZOTERO INTEGRATION. Harvard Bibliogr
- ZOTERO INTEGRATION. Harvard Bibliograp
- ZOTERO INTEGRATION. Harvard Bibliography

I am running Obsidian 0.15.9 (Flatpak), Zotero Integration 2.2.19.

**Comment by unamunoe** [comment]
As mentioned in #61, in my case the additional entries disappear when restarting Obsidian.

**Comment by mgmeyers** [comment]
This should be fixed now @NeoNewton01. Let me know if it still occurs.
