### ISSUE TITLE
Picture

### ISSUE THREAD

**Issue by einfachJens** [mgmeyers/obsidian-zotero-integration#81]
Pictures will Not Export

**Comment by tenglu0417** [comment]
Have the same issue, when insert the note locally, the image is not included.

**Comment by A-F-V** [comment]
Same

**Comment by Broadchurch95** [comment]
Same

**Comment by sylph520** [comment]
Same

**Comment by mgmeyers** [comment]
Images will now be imported when using the "Import Notes" and "Insert Notes Into Current Document" commands
