### ISSUE TITLE
Image Base Name on import formats do not work properly

### ISSUE THREAD

**Issue by ghost** [mgmeyers/obsidian-zotero-integration#84]
I am using Obsidian 0.15.9, Zotero Integration 2.2.20. The image base name on import formats do not work properly. I expected the output file to look like "**_image-1-x123-y456.jpg_**", but instead I get "**_5LI9AFTE.png_**". Templating on it also doesn't work.

**Comment by Solarrixs** [comment]
Same.
2.2.31 plugin version
v1.0.3 obsidian version

@MathematicsIncarnate Did you ever fix the issue?

**Comment by juandpinto** [comment]
Any intended fixes for this? Still happening.

**Comment by appwcn** [comment]
I expected the output file to look like "5LI9AFTE.png" rather than "image-1-x123-y456.jpg". How can I do this?
