### ISSUE TITLE
[Feature request] Select from citation list within command palette instead of zotero popup dialog box

### ISSUE THREAD

**Issue by supersistence** [mgmeyers/obsidian-zotero-integration#85]
When using the [obsidian citation plugin](https://github.com/hans/obsidian-citation-plugin) one can search for references within obsidian's command palette. When using this zotero integration however a popup dialog box opens in zotero. The app switching adds friction and time that, for me at least, makes this great integration harder to adopt. 

Is there a setting option in existence or that could be added to allow for command palette based search?

**Comment by ghweili** [comment]
this feature is useful, especially if the database does not contain  the whole zotero library, but only a subfolder within the zotero library. I haven't tried yet, but I guess the current approach searches items from the whole library.

**Comment by mgmeyers** [comment]
@supersistence Unfortunately this is not something I will likely implement. I agree that it would be ideal for the search to be done all within obsidian, but the red search box that pops up comes directly from zotero and has several features that would be difficult if not impossible to replicate without extending zotero with a custom plugin. Though, I'd be happy to accept a PR for this if someone wanted to implement it.
