### ISSUE TITLE
note creation and data explorer fail with "cannot read properties of undefined"

### ISSUE THREAD

**Issue by sirpbele** [mgmeyers/obsidian-zotero-integration#86]
Hi :) 

I didn't use this plugin for a couple of weeks and I didn't change anything in the settings (as far as I can remember). Now, when I tried to create a note from a Zotero reference, it fails with the error message. 

"Error retrieving item data: Cannot read properties of undefined (reading '2')"

The same error appears when I try the data explorer, with both my import template and preview import format.

I updated all plugins and obsidian and checked for Zotero updates, this didn't solve the problem.

I installed some Obsidian Plugins in the meantime: DB Folder, Pandoc Plugin; But I tried enabling one plugin at a time, restarting obsidian and creating a reference note - it didn't work.

Obsidian v0.15.9
Zotero 6.0.10

If I can provide any further information, please let me know.

**Comment by mgmeyers** [comment]
Hi @sirpbele Can you try updating the better bibtex plugin and see if that fixes this for you?

**Comment by sirpbele** [comment]
Hi @mgmeyers

Yes, this solved the issue. Thank you :) I tried updating right after I noticed the problem (03.08) but since then 2 or 3 newer versions were released and it's working again now after the udate to 6.7.21
