### ISSUE TITLE
How to Title Case the template tag {{title}}

### ISSUE THREAD

**Issue by pastorjack** [mgmeyers/obsidian-zotero-integration#87]
The nunjucks templating documenation has a "capitalize" function, but I can't find a function to title case (meaning each word is capitalized).

**Comment by mgmeyers** [comment]
@pastorjack It looks like there's a `title` function that does what you're looking for: https://mozilla.github.io/nunjucks/templating.html#title

Eg. `{{myValue | title}}`

**Comment by pastorjack** [comment]
perfect! Thank you!
