### ISSUE TITLE
[Error] Error when trying to configure PDF utility

### ISSUE THREAD

**Issue by nha4601** [mgmeyers/obsidian-zotero-integration#89]
Hello,

See console image below when trying to "Download" PDF utility. Note- I have manually downloaded this- but not sure how to configure the plugin...

![ObsidianError](https://user-images.githubusercontent.com/6230504/190400680-ca7316fa-5006-4269-bf79-d56626691d51.PNG)

**Comment by mgmeyers** [comment]
Hmm, it looks like github.com may be blocked for you for some reason? If you were able to download pdfannots2json, all you need to do is put it in `<vault>/.obsidian/plugins/obsidian-zotero-desktop-connector/` and it should work
