### ISSUE TITLE
Undefined error for data explorer and bibliography

### ISSUE THREAD

**Issue by Cutuchiqueno** [mgmeyers/obsidian-zotero-integration#9]
`Bibliography` and `Data Explorer` always throw the exception  below, for all entries in my Zotero:

![grafik](https://user-images.githubusercontent.com/306064/160391825-3160655b-df8d-4836-86c8-22bae8e454ea.png)

`Inline` citation works well.

Windows  21H2 / Zotero 6.0.2-beta.3 / Obsidian 0.14.2

**Comment by Cutuchiqueno** [comment]
General:

![grafik](https://user-images.githubusercontent.com/306064/160465741-90a45ea5-2e3c-4606-8545-cd1b98d6500f.png)

Not working *Citation Format*:

![grafik](https://user-images.githubusercontent.com/306064/160465944-9224a06f-bc08-4dc4-a71e-da7490b4b75d.png)

![grafik](https://user-images.githubusercontent.com/306064/160466736-a8f5f714-e1e7-4425-ab81-3539b2e65db7.png)

![grafik](https://user-images.githubusercontent.com/306064/160466859-44feb9ae-6e47-49eb-89e7-8ca0611ecd5a.png)

something else?

**Comment by mgmeyers** [comment]
Thanks, this is all very helpful. I can't seem to reproduce this, though. Could you try updating Zotero? I'm on 6.0.4 (not the beta) and it seems to work fine. It may also be a platform difference, so I'll have to do some more thorough testing on windows when I have some time this week.

<img width="141" alt="Screen Shot 2022-03-28 at 12 13 54 PM" src="https://user-images.githubusercontent.com/2694747/160470018-acb4b7c5-9c33-493a-9f8c-2f8260c7289c.png">

**Comment by Cutuchiqueno** [comment]
Unfortunately, it is not that easy to revert from beta version to production version. According to the Zotero forums one would need a complete reinstall.

I can also test my configuration on my PopOS 21.10 Linux machine. Most parameters and versions are the same. It maybe might suggest if it hast to do with the platfrom or my configuration.

**Comment by Cutuchiqueno** [comment]
PopOS 21.10 / Zotero 6.0.4 (NOT beta) / BetterBibTex 6.3.0 / Obsidian 0.14.3 / Zotero Desktop Connector 1.1.3: **same problem**

There is also a nice additional error message for the *Data Explorer* when the entry has an attachment:

![image](https://user-images.githubusercontent.com/306064/160481106-257c5ede-6d2a-4bfa-87a4-4270a2270c07.png)

**Comment by danieltomasz** [comment]
I dont know, but could you try with a new empty test profile with maybe 1 position? https://www.zotero.org/support/kb/multiple_profiles

**Comment by mgmeyers** [comment]
Hmm, so the second error there is another bug that I'll look into. The original error seems to be that zotero is returning an empty bibliography when we expect one to exist. I'll have to play around with this a bit and see why this might be.

**Comment by mgmeyers** [comment]
@Cutuchiqueno Just to check, are you able to copy a bibliography for an item from the edit menu in Zotero?

<img width="356" alt="Screen Shot 2022-03-31 at 1 38 15 PM" src="https://user-images.githubusercontent.com/2694747/161145157-307e57e6-b335-42dd-afb3-b33e9cc46b9f.png">

Another user was some how able to fix this issue after getting that to work: https://github.com/mgmeyers/obsidian-zotero-desktop-connector/issues/17

I'm still trying to figure out what's going on here...

**Comment by Cutuchiqueno** [comment]
Indeed, it appeas to be the same situation. I also have no entries for Copy Citation / Copy Bibliography in the menu:

![grafik](https://user-images.githubusercontent.com/306064/161152225-1c9a0264-d19f-433a-8d12-960dbcdcd913.png)

But I habe no clue how to get to it. I tested some configuration with BetterBibTex and Zoter, but without success. Nothing brings these items up in the menu. Nonethelless, seems to be a configuration issue though, does it not?

**Comment by Cutuchiqueno** [comment]
😄 and it works.  I was just messing with the BetterBibTex Export configuration. But it is the `Item Format` configuration in Zotero's Export tab that matters. I had "Better BibTex Select Link" selected. After changing that to Chicago the entries appear in the "Edit" tab and the Zotero Connector works. Thx!!! You can close the Issue if you want.

**Comment by WildOsk** [comment]
So, to sum up the trouble was Zotero's Export config, could you add a picture where to change it, because i did it yesterday and i didn't know exactly where it was. Thank you

**Comment by Cutuchiqueno** [comment]
**Preferences -> Export -> Item Format** is *not* allowed to have the value `Better BibTex Select Link`

![grafik](https://user-images.githubusercontent.com/306064/161275116-528d527f-752e-4320-882a-e99161e16c53.png)

**Comment by mgmeyers** [comment]
I've recently made an update that should fix this when the format for a bibliography is selected in the plugin settings. Let me know if any of you still have issues with it

**Comment by Cutuchiqueno** [comment]
Zoter-Connector-Desktop version 1.2.7: works for Bibliography, samme error for Data Explorer.

**Comment by jackspp** [comment]
https://github.com/mgmeyers/obsidian-zotero-desktop-connector/issues/9#issuecomment-1081107907
same problem here. Does anyone have a solution ? thanks

**Comment by mgmeyers** [comment]
@jackspp What is your quick copy setting set to in Zotero?

<img width="703" alt="Screen Shot 2022-04-17 at 9 22 26 AM" src="https://user-images.githubusercontent.com/2694747/163723376-6c7e3b44-9b75-46dc-85d9-7c60c34ff0b6.png">

And, if it's not blank, what CSL style did you choose in your bibliography settings?

<img width="675" alt="Screen Shot 2022-04-17 at 9 23 24 AM" src="https://user-images.githubusercontent.com/2694747/163723430-917ddb98-99b3-4bf0-8959-e7f63c7ce976.png">

**Comment by jackspp** [comment]
> @jackspp What is your quick copy setting set to in Zotero?
> 
> <img alt="Screen Shot 2022-04-17 at 9 22 26 AM" width="703" src="https://user-images.githubusercontent.com/2694747/163723376-6c7e3b44-9b75-46dc-85d9-7c60c34ff0b6.png">
> 
> And, if it's not blank, what CSL style did you choose in your bibliography settings?
> 
> <img alt="Screen Shot 2022-04-17 at 9 23 24 AM" width="675" src="https://user-images.githubusercontent.com/2694747/163723430-917ddb98-99b3-4bf0-8959-e7f63c7ce976.png">

thanks for quick reply. 
I met the second problem,  and `fitz: can't open document` happened.

**Comment by mgmeyers** [comment]
I see @jackspp, Could you open a separate issue for that? Perhaps sharing the PDF in question of you're able

**Comment by Krasser01** [comment]
Figured Out the Answer!

In Zotero make sure that Author is 'lastname/firstname'

else Author will return an undefined string.

**Comment by FabNTes** [comment]
Hello
It seems to be that I have the same issue.
I have better bibtex 6.7.43 installed.
This is my Zotero export format :
![image](https://user-images.githubusercontent.com/116300575/208529477-055e0804-1188-492c-92e4-e7a833f10fa4.png)

This is my setting in obsidian plugin 
![image](https://user-images.githubusercontent.com/116300575/208530075-3bae930a-1293-4c2e-8883-399394a6cac1.png)

This are the error messages I have in obsidian when I try to import my notes from zotero
![image](https://user-images.githubusercontent.com/116300575/208530486-ef15af5c-23fb-40cb-a84d-ea654b900e4c.png)

Precisions : I do have quick copy available in zotero
![image](https://user-images.githubusercontent.com/116300575/208530803-c59ac448-5a19-4689-80b7-2bdd9678c160.png)

And I do have 2 fields for author name in zotero.

If I import the data with the obsidian plugin (Zotero Data Explorer), it does show me every thing from the book 
![image](https://user-images.githubusercontent.com/116300575/208535222-ffa2d128-77cc-4a29-8b54-872db90d633d.png)

So everything seems to be ok but it doesn't import from zotero to my note...
What I can do with the plugin : cite / bibliography / import notes... but I can't have a formated import (I'm triyin to use the template you gave in another thread as you can see). In yellow what works.
![image](https://user-images.githubusercontent.com/116300575/208537992-6a454e2b-8f02-44e9-8a90-7aec076a057f.png)

My import format settings : 
![image](https://user-images.githubusercontent.com/116300575/208538358-e73aeb65-6526-40a1-9dad-5b2a5efbf5a5.png)
![image](https://user-images.githubusercontent.com/116300575/208538448-68ed6faa-4572-44f5-968e-4cb1457382c6.png)


I don't know how to fix this. Could you please help ?

**Comment by mgmeyers** [comment]
@FabNTes Please update this plugin and better bibtex and see if that helps

**Comment by FabNTes** [comment]
Thank you very much ! It worked.
