### ISSUE TITLE
[Feature Request] Import of Zotero tags

### ISSUE THREAD

**Issue by nha4601** [mgmeyers/obsidian-zotero-integration#90]
Hello,

Suggested feature: Support import of Zotero tags from parent item to Obsidian tags... Automatically create Obsidian tags from existing Zotero tags.

**Comment by lguenth** [comment]
You can already do this. The tags are stored in `{{allTags}}`.

**Comment by marcochristian** [comment]
Hello
If I have a string of tags, is it possible to separate them and then put them in [[tag]] so that an entry is created or linked. 
Best regards
Chris

**Comment by jankap** [comment]
@marcochristian 
You should be able to iterate through them.

In the Zotero Data Explorer, there's a field `allTags` containing a string
![image](https://user-images.githubusercontent.com/12893844/211907692-080a9e2e-9b08-4802-9e49-88f13efdc4bb.png)

But there's also an array of tags:
![image](https://user-images.githubusercontent.com/12893844/211907754-906906f1-5609-41a0-88de-cd9312089953.png)

You should be able to do something like in your template file:

```
{%- for tag in tags %}
[[{{tag.tag}}]]
{%- endfor -%}
```

This will create such an output:
![image](https://user-images.githubusercontent.com/12893844/211908218-6a359a3d-e4fe-42cd-a5f8-08b9c3398570.png)
