### ISSUE TITLE
is a fix possible for duplicate sets of annotations rendered when using Adobe Acrobat and Annotations notes?

### ISSUE THREAD

**Issue by wjfeeney** [mgmeyers/obsidian-zotero-integration#92]
My template uses two sections: one called "Annotations" incorporating {{annotation.annotatedText}} to capture annotations, and the other called "Notes" incorporating {{note.note}} to capture notes.

In Zotero, I use Adobe Acrobat, not Zotero's PDF Reader, to annotate my pdf's. Acrobat, at the moment, provides a little more flexibility. If I create an Annotations note in Zotero after making my annotations, and then import my annotations into Obsidian using Zotero Integration, I get two (2) identical sets of annotations in my Annotations section, one full set on top of the other set--presumably one set from the pdf, and the other set from the Annotations note. If I do NOT create an Annotations note, then Zotero Integration produces only one set of annotations.

By way of comparison, if I use Zotero's PDF Reader to make annotations, only one set of annotations is rendered whether or not I create an Annotations note. 

Annotations notes in Zotero are helpful to see annotations rather than scrolling through the pdf; and they are needed when using Zotero's export functions, for example, sending annotations and notes to destinations other than Obsidian.

I want to continue using Acrobat rather than Zotero, and would like Zotero Integration to pull Acrobat annotations from either the pdf or the Annotations note, but not both. It seems that Zotero Integration should work the same for both Acrobat-made and Zotero-made annotations. Is this possible?

**Comment by mgmeyers** [comment]
> By way of comparison, if I use Zotero's PDF Reader to make annotations, only one set of annotations is rendered whether or not I create an Annotations note.

I'm not exactly sure what you mean by this @wjfeeney. What does the data explorer show under the `notes` field for this PDF?

In my tests "Add note from annotation" in Zotero creates a note regardless of where the annotations were created. I also see that `annotations` is populated at the same time, thus the data is duplicated. If you want to bring in notes that aren't created using "Add note from annotation", you could filter them out like so:

```
{% for note in notes %}
{% if not note.note.startsWith("# Annotation") %}
{{note.note}}
{% endif %}
{% endfor %}
```

This says "output all notes that do not start with `# Annotation`". Is this what you're hoping to do?

**Comment by wjfeeney** [comment]
First, thank you for the template filtering notes! That solves one issue for me. 

However, the main issue  ("is a fix possible…") concerns duplicate highlights and comments when using Adobe Acrobat.

This is the part of my template to capture my highlights and comments:

### Annotations
{% for annotation in annotations %}
{% if annotation.annotatedText %}
{{annotation.annotatedText}}
{% endif %}
{% if annotation.comment %}
{{annotation.comment}}
{% endif %}
{% endfor %}

I've attached screen shots of the outputs (1) when I "Add Note from Annotation," and (2) when I do not "Add Note from Annotation." I've also attached three (3) screenshots of what is shown in the data explorer.

When I use Acrobat to make my annotations, and then "Add Note from Annotations," and then use Zotero Integration to import my annotations into Obsidian, the output is duplicate highlights and comments. (see screenshot)

If I do NOT "Add Note from Annotations," the output appears properly, no duplicates, as expected. (see screenshot)

The solution I am seeking: I want to be able to use Adobe Acrobat to make annotations, and "Add Note from Annotation" without seeing duplicate highlights/comments in Zotero Integration's output. The Annotation note in Zotero is helpful in several ways, and I want to be able to continue using them. By way of comparison, as I stated, if I use Zotero's PDF Reader to make annotations and also "Add Note from Annotation," there are no duplicates. I prefer Acrobat, and would like parity of output.

Thank you for helping me with this.
Bill

**Comment by wjfeeney** [comment]
I am sorry to bother you, but the template you provided below does not work to exclude notes that start with Annotation. Those notes are still in the output.

**Comment by mgmeyers** [comment]
@wjfeeney Could you share some additional info:

1. Your template
2. An example of the output with duplicate content
3. Screenshots of the annotations and notes in Data Explorer, eg:

<img width="577" alt="Screen Shot 2022-09-23 at 9 53 38 AM" src="https://user-images.githubusercontent.com/2694747/192012591-98c5da62-11a0-4117-9751-3881e96b83cb.png">

<img width="833" alt="Screen Shot 2022-09-23 at 9 54 24 AM" src="https://user-images.githubusercontent.com/2694747/192012713-4ffbff7a-b169-4ba4-aa22-5bf3eb0f0058.png">

**Comment by wjfeeney** [comment]
**MY TEMPLATE** - I disabled the persist part.

```
## {{title}}

<hr style="width:100%; margin-left: auto; margin-right: auto; border-color: rgb(158, 53, 44);">


### Bibliography

{{bibliography}}
{% if abstractNote %}

### Abstract

{{abstractNote}}
{% endif %}


### <span style="border-bottom: 2px solid #9E352C;">Annotations</span>

{# {% persist "annotations" %} 
{% set annotations = annotations | filterby("date", "dateafter", lastImportDate) -%} 
{% if annotations.length > 0 %}
###### Imported on {{importDate | format("YYYYMMDD h:mm a")}}#}

{% for annotation in annotations %}
{% if annotation.annotatedText %}
<mark style="background: {{annotation.color}}">{{annotation.annotatedText}}</mark> [(p. {{annotation.page}})](zotero://open-pdf/library/items/{{annotation.attachment.itemKey}}?page={{annotation.page}}) 
{% endif %}
{% if annotation.comment %} 
>{{annotation.comment}} [(p. {{annotation.page}})](zotero://open-pdf/library/items/{{annotation.attachment.itemKey}}?page={{annotation.page}}) 

{% endif %}
{% endfor %}
{#{% endif %}
{% endpersist %}#}

### <span style="border-bottom: 2px solid #9E352C;">Notes</span>

{% for note in notes %}
{% if note.note %}
{{note.note}}
<hr>
{% endif %}
{% endfor %}
```

**OUTPUT WITH DUPLICATE CONTENT**

<img width="564" alt="1_Duplicate annotations" src="https://user-images.githubusercontent.com/51898950/192070401-5c19c627-6ae2-4c8e-9bcf-96a53a73f7d1.png">

<img width="569" alt="2_Notes under duplicate annotations" src="https://user-images.githubusercontent.com/51898950/192070447-118fc2d9-4c5e-4ce0-9ec8-acaafed2089d.png">


**OUTPUT WITHOUT DUPLICATE CONTENT**
 
![output without Annotations note](https://user-images.githubusercontent.com/51898950/192070639-8475d57e-b96f-4714-b310-3f904a04ceb5.png)


**ANNOTATIONS AND NOTES IN DATA EXPLORER**

<img width="536" alt="data explorer_annots_0_1" src="https://user-images.githubusercontent.com/51898950/192070561-00fdc071-682e-42d7-b2d6-8194e6e19040.png">
<img width="534" alt="data explorer_annots__2_3" src="https://user-images.githubusercontent.com/51898950/192070569-f6c81e3c-8c4d-4573-a280-196354761aa9.png">
<img width="521" alt="data explorer_annots__4_5" src="https://user-images.githubusercontent.com/51898950/192070583-59b3a93a-b7f8-45f9-a4ab-610b87b58e25.png">
<img width="524" alt="data explorer_notes_0_1" src="https://user-images.githubusercontent.com/51898950/192070590-149f7468-74d6-408c-b4a0-642dcdc9a730.png">
<img width="512" alt="data explorer_notes_2_3" src="https://user-images.githubusercontent.com/51898950/192070601-bf3729a5-0387-4b40-b4e2-28329cb47d66.png">
<img width="522" alt="data explorer_notes_4_5" src="https://user-images.githubusercontent.com/51898950/192070610-75f199ed-a870-4693-bd89-efd2b2d80037.png">

**Comment by wjfeeney** [comment]
By the way, the code you provided above (set set forth below) does not work to exclude Annotations notes from the output, i.e., the output includes Annotations notes.

```
{% for note in notes %}
{% if not note.note.startsWith("# Annotation") %}
{{note.note}}
{% endif %}
{% endfor %}
```

**Comment by mgmeyers** [comment]
Perfect, I see what's going on now.

So, first, it looks like your annotation note starts with `**Annotations` rather than `# Annotation`:

<img width="465" alt="Screen Shot 2022-09-23 at 5 19 46 PM" src="https://user-images.githubusercontent.com/2694747/192071779-7faf50c2-84bb-45aa-8eb0-2eb3bf36cabf.png">

To filter this out, you would do:

```
{% for note in notes %}
{% if not note.note.startsWith("**Annotation") %}
{{note.note}}
{% endif %}
{% endfor %}
```

Next, it looks like annotations from zotero and the PDF itself are included in the annotations list, which is why you have duplicates. I've added a new field called `source` to annotations so you can tell where they come from:


<img width="513" alt="Screen Shot 2022-09-23 at 5 19 08 PM" src="https://user-images.githubusercontent.com/2694747/192071909-a76c2e31-a731-4b6d-b9d3-279d2014418f.png">

Since you're wanting to use Acrobat for annotations, I'd recommend filtering your annotations to only include ones with `pdf` as their source like so:

```
{% set annotations = annotations | filterby("date", "dateafter", lastImportDate) -%} 
{% set annotations = annotations | filterby("source", "startswith", "pdf") -%} 
```

Let me know if this works for you.

**Comment by wjfeeney** [comment]
Will do…and report back. This is going to make such a difference. Thanks.

The first line above is for the persist part, right? That's my templatte.

Where do I put the second line?

**Comment by mgmeyers** [comment]
@wjfeeney Great to hear! Glad we were able to figure out a solution. Let me know if you run into any other issues.

**Comment by jankap** [comment]
Just found this ticket by coincidence. I'm wondering: Is there any need to create notes (I do not mean annotations in the PDF) in Zotero? Even PDF annotations from Acrobat should appear as annotations linked to the PDF.

Is the assumption correct that I do not need any distinct notes anymore?

Thanks for your wonderful plugin @mgmeyers ❤️
