### ISSUE TITLE
FR: Open (last created) note after import

### ISSUE THREAD

**Issue by lguenth** [mgmeyers/obsidian-zotero-integration#94]
Hey mgmeyers :blush: 

Something I've been thinking about for a while now is that I would like to have an option to automatically open the note I just imported, similar to how QuickAdd can jump to the note on capture.

It would be nice to have this as a toggle-able option. When importing multiple notes, it might be more logical to open the one that was created last.

What do you think of the idea? Would that be implement-able? (If I have the time I'll look through the code a bit.)

**Comment by erazlogo** [comment]
+1 I have been thinking about this also :) It would also be nice also to set where to open it--the current pane or a new tab, for example.

**Comment by mgmeyers** [comment]
This has been implemented!
