### ISSUE TITLE
Error Processing PDF: Command failed with EACCES

### ISSUE THREAD

**Issue by csducate** [mgmeyers/obsidian-zotero-integration#95]
I'm trying to get OZI set up on a new computer, but when I go to extract annotations, I get "Error Processing PDF: Command failed with EACCES". The problem occurs with every PDF I've tried. 

<img width="338" alt="Screen Shot 2022-09-23 at 9 36 52 AM" src="https://user-images.githubusercontent.com/48921940/191991247-bab3c31d-87ef-4632-82ff-1057ef498696.png">

I've tried to Google what EACCES is to troubleshoot myself, but I'm stumped. Any help or advice on how to fix the problem?

**Comment by mgmeyers** [comment]
I believe this means that obsidian doesn't have permissions to access to the PDF extraction utility `pdfannots2json` for some reason. Is your vault synced between multiple devices? You could try deleting `/Users/cducate/Documents/Knowledge Hub/.obsidian/plugins/obsidian-zotero- desktop-connector/pdfannots2json` and reinstalling it from the plugin settings.

**Comment by csducate** [comment]
Aha! Deleting and reinstalling worked! Would not have thought of that. Thank you!
