### ISSUE TITLE
keywords on papers

### ISSUE THREAD

**Issue by D4san** [mgmeyers/obsidian-zotero-integration#96]
Hi, anyone knows how can i or it is possible import the keywords from papers? I cant find a templating in the data explorer how reference this. 

For example...

![image](https://user-images.githubusercontent.com/114251096/193495888-7c1c16c2-163e-420d-adcb-2b033710d644.png)

of course i can do it withcreative metods... but...

**Comment by mgmeyers** [comment]
This is not something that can be extracted automatically, but you could add these as tags to the item in Zotero, then they could be imported using a template
