### ISSUE TITLE
Path messed up for image import 

### ISSUE THREAD

**Issue by p-sin** [mgmeyers/obsidian-zotero-integration#99]
OS: Linux
Feature: Import Formats/Template

There's a weird bug concerning the image import through `pdfannots2json`. The issue seems to be caused by passing it a relative path via the `ImageOutputPath` parameter. I'm not sure if this issue should rather be in that repo.

Assuming my vault is under `/home/user/notes/`, and my Image Output Path is just `images`, instead of saving the image relative to the Obsidian vault `/home/user/notes/images/`, it saves the file under `/home/user/home/user/notes/images/`.

It appears like `pdfannots2json` expects a relative parameter but receives an absolute one.

The problem can be avoided by launching Obsidian from the root directory `/`. Would be nice to have a better solution though.

**Comment by mmbcorley** [comment]
I have exactly the same problem (also on Linux).  Can add that giving an absolute path (e.g., `/home/user/notes/images/`) in the preferences doesn't help either.

**Comment by sevadah** [comment]
I am having the same issue. What I can add is that if I use the `flatpak` version (I am on Fedora 36) the new folder is create in my home directory. I tried with an `Appimage`, which was located in my `Downloads` folder,  the "new" `home` folder is created in my `Downloads` folder.

Thus it seems that as a starting point for the path it takes the location of launcher.  I guess if someone uses the deb file to install, it should work properly.

The solution probably would be to set the launcher in the `bin` directory under root?

**Comment by p-sin** [comment]
I have no experience with `flatpak`, but what I did is that I just made a corresponding `.desktop` file as dirty workaround:

`~/.local/share/applications/obsidian.desktop`
```[Desktop Entry]
Name=Obsidian
Exec=bash -c 'cd / && /usr/bin/obsidian %U'
Terminal=false
Type=Application
Icon=obsidian
StartupWMClass=obsidian
Comment=Obsidian
MimeType=x-scheme-handler/obsidian;
Categories=Office;```

**Comment by sevadah** [comment]
Thanks a lot! I'll give it a shot. Just to clarify: you have put `obsidian.appimage` into the `/usr/bin/` or are you using the binaries from the deb file?

**Comment by p-sin** [comment]
> Thanks a lot! I'll give it a shot. Just to clarify: you have put `obsidian.appimage` into the `/usr/bin/` or are you using the binaries from the deb file?

I'm not sure how exactly AppImages work (I suppose it is a container?), as I installed Obsidian via my package manager (pacman), which installed the Obsidian binary to `/usr/bin/obsidian`.

**Comment by sevadah** [comment]
> I'm not sure how exactly AppImages work (I suppose it is a container?), 

Yes, something similar. It is basically executable that contains all dependencies and distro-agnostic. 

>as I installed Obsidian via my package manager (pacman), which installed the Obsidian binary to /usr/bin/obsidian.

I see. Thanks, I'll try to find a workaround for appimage or flatpak.

**Comment by mgmeyers** [comment]
Thanks for looking into this you all. I'm not exactly sure what's going on here. The code firsts processes the image output path template, then calls `path.resolve(vaultRoot, imageOutputPath)`. This (at least on mac and windows) results in an absolute path that is passed to `pdfannots2json`. 

If any of you are code savvy, here's where this happens: https://github.com/mgmeyers/obsidian-zotero-integration/blob/main/src/bbt/export.ts#L521-L537

**Comment by mgmeyers** [comment]
Actually, I think I figured it out. Obsidian has a `normalizePath` function I was using, and it seems this was stripping out the starting slash in the file path. I've removed this. Let me know if images work for you now.

**Comment by p-sin** [comment]
This has solved the issue for me. Thanks!
